trigger:
- feature/*

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:

    - checkout: self
      fetchDepth: 0

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sdk_sonar'
        organization: 'fastpix'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'FastPix_nodejs-sdk'
        cliProjectName: 'nodejs-sdk'
        extraProperties: |
          sonar.projectKey=FastPix_nodejs-sdk
          sonar.organization=fastpix
          sonar.projectName=nodejs-sdk
          sonar.sources=.

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'

    - script: npm install
      displayName: 'Install Dependencies'

    - task: SonarCloudAnalyze@1

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'