/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import { livePlaybackCreateId } from "../funcs/livePlaybackCreateId.js";
import { livePlaybackDelete } from "../funcs/livePlaybackDelete.js";
import { livePlaybackGet } from "../funcs/livePlaybackGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class LivePlayback extends ClientSDK {
  /**
   * Create a playbackId
   *
   * @remarks
   * Generates a new playback ID for the live stream, allowing viewers to access the stream through this ID. The playback ID can be shared with viewers for direct access to the live broadcast.
   *
   *   By calling this endpoint with the `streamId`, FastPix returns a unique `playbackId`, which can be used to stream the live content.
   *
   *   #### Example
   *
   *   A media platform needs to distribute a unique playback ID to users for an exclusive live concert. The platform can also embed the stream on various partner websites.
   */
  async createId(
    request: operations.CreatePlaybackIdOfStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.CreatePlaybackIdOfStreamResponse> {
    return unwrapAsync(livePlaybackCreateId(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a playbackId
   *
   * @remarks
   * Deletes a previously created playback ID for a live stream.This prevents new viewers from accessing the stream using the playback ID, while current viewers can continue watching for a short period before the connection ends. FastPix deletes the ID and ensures the new playback request fails.
   *
   * #### Example
   * A streaming service wants to prevent new users from joining a live stream that is nearing its end. The host can delete the playback ID to ensure no one can join the stream or replay it once it ends.
   */
  async delete(
    request: operations.DeletePlaybackIdOfStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.DeletePlaybackIdOfStreamResponse> {
    return unwrapAsync(livePlaybackDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get playbackId details
   *
   * @remarks
   * Retrieves details for an existing playback ID. When you provide the playbackId returned from a previous stream or playback creation request, FastPix returns the associated playback information, including the access policy.
   *
   * #### Example
   * A developer needs to confirm the access policy of the playback ID to ensure whether the stream is public or private for viewers.
   */
  async get(
    request: operations.GetLiveStreamPlaybackIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetLiveStreamPlaybackIdResponse> {
    return unwrapAsync(livePlaybackGet(
      this,
      request,
      options,
    ));
  }
}
