/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import { playbackCreate } from "../funcs/playbackCreate.js";
import { playbackDelete } from "../funcs/playbackDelete.js";
import { playbackGet } from "../funcs/playbackGet.js";
import { playbackListIds } from "../funcs/playbackListIds.js";
import { playbackUpdateDomainRestrictions } from "../funcs/playbackUpdateDomainRestrictions.js";
import { playbackUpdateUserAgentRestrictions } from "../funcs/playbackUpdateUserAgentRestrictions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Playback extends ClientSDK {
  /**
   * Create a playback ID
   *
   * @remarks
   * You can create a new playback ID for a specific media asset. If you have already retrieved an existing `playbackId` using the <a href="https://docs.fastpix.io/reference/get-media">Get Media by ID</a> endpoint for a media asset, you can use this endpoint to generate a new playback ID with a specified access policy.
   *
   * If you want to create a private playback ID for a media asset that already has a public playback ID, this endpoint also allows you to do so by specifying the desired access policy.
   *
   * #### How it works
   *
   * 1. Make a `POST` request to this endpoint, replacing `<mediaId>` with the `uploadId` or `id` of the media asset.
   *
   * 2. Include the `accessPolicy` in the request body with `private` or `public` as the value.
   *
   * 3. You receive a response containing the newly created playback ID with the specified access level.
   *
   * #### Example
   * A video streaming service generates playback IDs for each media file when users request to view specific content. The video player then uses the playback ID to stream the video.
   */
  async create(
    request: operations.CreateMediaPlaybackIdRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateMediaPlaybackIdResponse> {
    return unwrapAsync(playbackCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all playback IDs details for a media
   *
   * @remarks
   * Retrieves all playback IDs associated with a given media asset, including each playback ID’s access policy and detailed access restrictions such as allowed or denied domains and user agents.
   *
   * **How it works:**
   * 1. Send a `GET` request to this endpoint with the target `mediaId`.
   * 2. The response includes an array of playback ID records with their respective access controls.
   *
   * **Use case:**
   * Useful for validating and managing playback permissions programmatically, reviewing restriction settings, or powering an access control dashboard.
   */
  async listIds(
    request: operations.ListPlaybackIdsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListPlaybackIdsResponse> {
    return unwrapAsync(playbackListIds(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a playback ID
   *
   * @remarks
   * This endpoint deletes a specific playback ID associated with a media asset. Deleting a `playback ID` revokes access to the media content linked to that ID.
   *
   * #### How it works
   *
   * 1. Make a `DELETE` request to this endpoint, replacing `<mediaId>` with the unique ID of the media asset from which you want to delete the playback ID.
   *
   * 2. Include the `playbackId` you want to delete in the request body.
   *
   * #### Example
   *
   * Your platform offers limited-time access to premium content. When the subscription expires, you can revoke access to the content by deleting the associated playback ID, preventing users from streaming the video further.
   */
  async delete(
    request: operations.DeleteMediaPlaybackIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteMediaPlaybackIdResponse> {
    return unwrapAsync(playbackDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a playback ID
   *
   * @remarks
   * This endpoint retrieves details about a specific playback ID associated with a media asset. Use it to check the access policy for that specific playback ID, such as whether it is public or private.
   *
   * **How it works:**
   * 1. Make a GET request to the endpoint, replacing `{mediaId}` with the media ID and `{playbackId}` with the playback ID.
   * 2. This request is useful for auditing or validation before granting playback access in your application.
   *
   * **Example:**
   * A media platform might use this endpoint to verify if a playback ID is public or private before embedding the video in a frontend player or allowing access to a restricted group.
   */
  async get(
    request: operations.GetPlaybackIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPlaybackIdResponse> {
    return unwrapAsync(playbackGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update domain restrictions for a playback ID
   *
   * @remarks
   * This endpoint updates domain-level restrictions for a specific playback ID associated with a media asset.
   * It allows you to restrict playback to specific domains or block known unauthorized domains.
   *
   * **How it works:**
   * 1. Make a `PATCH` request to this endpoint with your desired domain access configuration.
   * 2. Set a default policy (`allow` or `deny`) and specify domain names in the `allow` or `deny` lists.
   * 3. This is commonly used to restrict video playback to your website or approved client domains.
   *
   * **Example:**
   * A streaming service can allow playback only from `example.com` and deny all others by setting: `"defaultPolicy": "deny"` and `"allow": ["example.com"]`.
   */
  async updateDomainRestrictions(
    request: operations.UpdateDomainRestrictionsRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateDomainRestrictionsResponse> {
    return unwrapAsync(playbackUpdateDomainRestrictions(
      this,
      request,
      options,
    ));
  }

  /**
   * Update user-agent restrictions for a playback ID
   *
   * @remarks
   * This endpoint allows updating user-agent restrictions for a specific playback ID associated with a media asset.
   * It can be used to allow or deny specific user-agents during playback request evaluation.
   *
   * **How it works:**
   * 1. Make a `PATCH` request to this endpoint with your desired user-agent access configuration.
   * 2. Specify a default policy (`allow` or `deny`) and provide specific `allow` or `deny` lists.
   * 3. Use this to restrict access to specific browsers, devices, or bots.
   *
   * **Example:**
   * A developer may configure a playback ID to deny access from known scraping user-agents while allowing all others by default.
   */
  async updateUserAgentRestrictions(
    request: operations.UpdateUserAgentRestrictionsRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateUserAgentRestrictionsResponse> {
    return unwrapAsync(playbackUpdateUserAgentRestrictions(
      this,
      request,
      options,
    ));
  }
}
