/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import { playlistCreate } from "../funcs/playlistCreate.js";
import { playlistDelete } from "../funcs/playlistDelete.js";
import { playlistGet } from "../funcs/playlistGet.js";
import { playlistList } from "../funcs/playlistList.js";
import { playlistUpdate } from "../funcs/playlistUpdate.js";
import { playlistUpdateMediaOrder } from "../funcs/playlistUpdateMediaOrder.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Playlist extends ClientSDK {
  /**
   * Create a new playlist
   *
   * @remarks
   * This endpoint creates a new playlist within a specified workspace. A playlist acts as a container for organizing media items either manually or based on filters and metadata. <br> <br>
   * ### Playlists can be created in two modes
   * - **Manual:** Creates an empty playlist without any initial media items. Use this mode for manual curation, where you add items later in a user-defined sequence.
   * - **Smart:** Auto-populates the playlist at creation time based on the filter criteria (for example, a video creation date range) that you provide in the request.
   *
   * For more details, see <a href="https://docs.fastpix.io/docs/create-and-manage-playlist">Create and manage playlist</a>.
   *
   * #### How it works
   *
   *  - When you send a `POST` request to this endpoint, FastPix creates a playlist and returns a playlist ID, using which items can be added later in a user-defined sequence.
   *  - You can create a smart playlist that is auto-populated based on the metadata in the request body.
   *
   * #### Example
   * An e-learning platform creates a new playlist titled Beginner Python Series through the API. The response returns a unique playlist ID. The platform uses this ID to add a series of video tutorials to the playlist in a defined order. The playlist appears on the frontend as a structured learning path for learners.
   */
  async create(
    request: models.CreatePlaylistRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateAPlaylistResponse> {
    return unwrapAsync(playlistCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all playlists
   *
   * @remarks
   * This endpoint retrieves all playlists in a specified workspace. It allows you to view the collection of manual and smart playlists along with their associated metadata.
   * #### How it works
   *
   *  - When a user sends a GET request to this endpoint, FastPix returns a list of all playlists in the workspace, including details such as playlist IDs, titles, creation mode (manual or smart), and other relevant metadata.
   *
   * #### Example
   *
   *   An e-learning platform requests all playlists within a workspace to display an overview of available learning paths. The response includes multiple playlists like "Beginner Python Series" and "Advanced Java Tutorials," enabling the platform to show users a catalog of curated content collections.
   */
  async list(
    request?: operations.GetAllPlaylistsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetAllPlaylistsResponse> {
    return unwrapAsync(playlistList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a playlist by ID
   *
   * @remarks
   * This endpoint retrieves detailed information about a specific playlist using its unique `playlistId`. It provides comprehensive metadata about the playlist, including its title, creation mode (manual or smart), media items along with the metadata of each media in the playlist.
   *
   * #### Example
   * An e-learning platform requests details for the playlist "Beginner Python Series" by providing its unique `playlistId`. The response includes the playlist"s title, creation mode, and the ordered list of video tutorials contained within, enabling the platform to present the full learning path to users.
   */
  async get(
    request: operations.GetPlaylistByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPlaylistByIdResponse> {
    return unwrapAsync(playlistGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a playlist by ID
   *
   * @remarks
   * This endpoint allows you to update the name and description of an existing playlist. It enables modifications to the playlist's metadata without altering the media items or playlist structure.
   * #### How it works
   *
   *  - When a user sends a PUT request to this endpoint with the `playlistId` and updated name and description in the request body, FastPix updates the playlist metadata accordingly and returns the updated playlist details.
   *
   * #### Example
   * An e-learning platform updates the playlist titled "Beginner Python Series" to rename it as "Python Basics" and add a more detailed description. The updated metadata is reflected when retrieving the playlist, helping users better understand the playlist content.
   */
  async update(
    request: operations.UpdateAPlaylistRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateAPlaylistResponse> {
    return unwrapAsync(playlistUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a playlist by ID
   *
   * @remarks
   * This endpoint allows you to delete an existing playlist from the workspace. After deleted, the playlist and its metadata are permanently removed and cannot be recovered.
   * #### How it works
   *  - When a user sends a DELETE request to this endpoint with the `playlistId`, FastPix removes the specified playlist from the workspace and returns a confirmation of successful deletion.
   *
   * #### Example
   * An e-learning platform deletes an outdated playlist titled "Old Python Tutorials" by providing its unique playlist ID. The platform receives confirmation that the playlist has been removed, ensuring learners no longer see the obsolete content.
   */
  async delete(
    request: operations.DeleteAPlaylistRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteAPlaylistResponse> {
    return unwrapAsync(playlistDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Change media order in a playlist by ID
   *
   * @remarks
   * This endpoint allows you to change the order of media items within a playlist. By passing the complete list of media IDs in the desired sequence, the playlist's play order is updated accordingly.
   * #### How it works
   *
   *  - When a user sends a PUT request to this endpoint with the `playlistId` as path parameter and the reordered list of all media IDs in the request body, FastPix updates the playlist to reflect the new media sequence and returns the updated playlist details.
   *
   * #### Example
   * An e-learning platform rearranges the "Beginner Python Series" playlist by submitting a reordered list of media IDs. The playlist now follows the new sequence, providing learners with a better structured learning path.
   */
  async updateMediaOrder(
    request: operations.ChangeMediaOrderInPlaylistRequest,
    options?: RequestOptions,
  ): Promise<operations.ChangeMediaOrderInPlaylistResponse> {
    return unwrapAsync(playlistUpdateMediaOrder(
      this,
      request,
      options,
    ));
  }
}
