/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

export type APICall =
  | {
      status: "complete";
      request: Request;
      response: Response;
    }
  | {
      status: "request-error";
      request: Request;
      response?: undefined;
    }
  | {
      status: "invalid";
      request?: undefined;
      response?: undefined;
    };

export class APIPromise<T> extends Promise<T> {
  readonly #inspect: Promise<[T, APICall]>;

  override readonly [Symbol.toStringTag] = "APIPromise";

  // Derived promises (from then/catch/finally) must be plain Promises, not this
  // subclass, otherwise the runtime would re-invoke our constructor with an
  // executor function instead of the expected tuple/promise input.
  static override get [Symbol.species](): PromiseConstructor {
    return Promise;
  }

  constructor(p: [T, APICall] | Promise<[T, APICall]>) {
    const inspect = APIPromise.#asInspect(p);
    super(APIPromise.#executor(inspect));
    this.#inspect = inspect;
  }

  static #asInspect<T>(
    p: [T, APICall] | Promise<[T, APICall]>,
  ): Promise<[T, APICall]> {
    return p instanceof Promise ? p : Promise.resolve(p);
  }

  static #executor<T>(
    inspect: Promise<[T, APICall]>,
  ): (resolve: (value: T) => void, reject: (reason?: unknown) => void) => void {
    return (resolve, reject) => {
      inspect.then(([value]) => resolve(value), reject);
    };
  }

  $inspect(): Promise<[T, APICall]> {
    return this.#inspect;
  }
}
