/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddMediaToPlaylistRequest = {
  /**
   * The unique id of the playlist you want to perform the operation on.
   */
  playlistId: string;
  body: models.MediaIdsRequest;
};

export type AddMediaToPlaylistResponse =
  | models.PlaylistByIdResponse
  | models.DefaultError;

/** @internal */
export type AddMediaToPlaylistRequest$Outbound = {
  playlistId: string;
  body: models.MediaIdsRequest$Outbound;
};

/** @internal */
export const AddMediaToPlaylistRequest$outboundSchema: z.ZodMiniType<
  AddMediaToPlaylistRequest$Outbound,
  AddMediaToPlaylistRequest
> = z.object({
  playlistId: z.string(),
  body: models.MediaIdsRequest$outboundSchema,
});

export function addMediaToPlaylistRequestToJSON(
  addMediaToPlaylistRequest: AddMediaToPlaylistRequest,
): string {
  return JSON.stringify(
    AddMediaToPlaylistRequest$outboundSchema.parse(addMediaToPlaylistRequest),
  );
}

/** @internal */
export const AddMediaToPlaylistResponse$inboundSchema: z.ZodMiniType<
  AddMediaToPlaylistResponse,
  unknown
> = smartUnion([
  models.PlaylistByIdResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function addMediaToPlaylistResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddMediaToPlaylistResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddMediaToPlaylistResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddMediaToPlaylistResponse' from JSON`,
  );
}
