/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AddMediaTrackRequestBody = {
  /**
   * Contains details about the track being added to the media file.
   */
  tracks: models.AddTrackRequest;
};

export type AddMediaTrackRequest = {
  /**
   * The unique identifier assigned to the media when created. The value must be a valid UUID.
   */
  mediaId: string;
  body: AddMediaTrackRequestBody;
};

/**
 * Media details updated successfully
 */
export type AddMediaTrackResponseBody = {
  /**
   * Demonstrates whether the request is successful or not.
   */
  success?: boolean | undefined;
  /**
   * Contains details about the track that was added or updated.
   */
  data?: models.AddTrackResponse | undefined;
};

export type AddMediaTrackResponse =
  | AddMediaTrackResponseBody
  | models.DefaultError;

/** @internal */
export type AddMediaTrackRequestBody$Outbound = {
  tracks: models.AddTrackRequest$Outbound;
};

/** @internal */
export const AddMediaTrackRequestBody$outboundSchema: z.ZodMiniType<
  AddMediaTrackRequestBody$Outbound,
  AddMediaTrackRequestBody
> = z.object({
  tracks: models.AddTrackRequest$outboundSchema,
});

export function addMediaTrackRequestBodyToJSON(
  addMediaTrackRequestBody: AddMediaTrackRequestBody,
): string {
  return JSON.stringify(
    AddMediaTrackRequestBody$outboundSchema.parse(addMediaTrackRequestBody),
  );
}

/** @internal */
export type AddMediaTrackRequest$Outbound = {
  mediaId: string;
  body: AddMediaTrackRequestBody$Outbound;
};

/** @internal */
export const AddMediaTrackRequest$outboundSchema: z.ZodMiniType<
  AddMediaTrackRequest$Outbound,
  AddMediaTrackRequest
> = z.object({
  mediaId: z.string(),
  body: z.lazy(() => AddMediaTrackRequestBody$outboundSchema),
});

export function addMediaTrackRequestToJSON(
  addMediaTrackRequest: AddMediaTrackRequest,
): string {
  return JSON.stringify(
    AddMediaTrackRequest$outboundSchema.parse(addMediaTrackRequest),
  );
}

/** @internal */
export const AddMediaTrackResponseBody$inboundSchema: z.ZodMiniType<
  AddMediaTrackResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(models.AddTrackResponse$inboundSchema),
});

export function addMediaTrackResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AddMediaTrackResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddMediaTrackResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddMediaTrackResponseBody' from JSON`,
  );
}

/** @internal */
export const AddMediaTrackResponse$inboundSchema: z.ZodMiniType<
  AddMediaTrackResponse,
  unknown
> = smartUnion([
  z.lazy(() => AddMediaTrackResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function addMediaTrackResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddMediaTrackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddMediaTrackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddMediaTrackResponse' from JSON`,
  );
}
