/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ChangeMediaOrderInPlaylistRequest = {
  /**
   * The unique id of the playlist you want to perform the operation on.
   */
  playlistId: string;
  body: models.MediaIdsRequest;
};

export type ChangeMediaOrderInPlaylistResponse =
  | models.PlaylistByIdResponse
  | models.DefaultError;

/** @internal */
export type ChangeMediaOrderInPlaylistRequest$Outbound = {
  playlistId: string;
  body: models.MediaIdsRequest$Outbound;
};

/** @internal */
export const ChangeMediaOrderInPlaylistRequest$outboundSchema: z.ZodMiniType<
  ChangeMediaOrderInPlaylistRequest$Outbound,
  ChangeMediaOrderInPlaylistRequest
> = z.object({
  playlistId: z.string(),
  body: models.MediaIdsRequest$outboundSchema,
});

export function changeMediaOrderInPlaylistRequestToJSON(
  changeMediaOrderInPlaylistRequest: ChangeMediaOrderInPlaylistRequest,
): string {
  return JSON.stringify(
    ChangeMediaOrderInPlaylistRequest$outboundSchema.parse(
      changeMediaOrderInPlaylistRequest,
    ),
  );
}

/** @internal */
export const ChangeMediaOrderInPlaylistResponse$inboundSchema: z.ZodMiniType<
  ChangeMediaOrderInPlaylistResponse,
  unknown
> = smartUnion([
  models.PlaylistByIdResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function changeMediaOrderInPlaylistResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChangeMediaOrderInPlaylistResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChangeMediaOrderInPlaylistResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChangeMediaOrderInPlaylistResponse' from JSON`,
  );
}
