/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateNewStreamResponse =
  | models.LiveStreamResponseDTO
  | models.DefaultError;

/** @internal */
export const CreateNewStreamResponse$inboundSchema: z.ZodMiniType<
  CreateNewStreamResponse,
  unknown
> = smartUnion([
  models.LiveStreamResponseDTO$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function createNewStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateNewStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateNewStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateNewStreamResponse' from JSON`,
  );
}
