/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreatePlaybackIdOfStreamRequest = {
  /**
   * After creating a new live stream, FastPix assigns a unique identifier to the stream.
   */
  streamId: string;
  body: models.PlaybackIdRequest;
};

export type CreatePlaybackIdOfStreamResponse =
  | models.PlaybackIdSuccessResponse
  | models.DefaultError;

/** @internal */
export type CreatePlaybackIdOfStreamRequest$Outbound = {
  streamId: string;
  body: models.PlaybackIdRequest$Outbound;
};

/** @internal */
export const CreatePlaybackIdOfStreamRequest$outboundSchema: z.ZodMiniType<
  CreatePlaybackIdOfStreamRequest$Outbound,
  CreatePlaybackIdOfStreamRequest
> = z.object({
  streamId: z.string(),
  body: models.PlaybackIdRequest$outboundSchema,
});

export function createPlaybackIdOfStreamRequestToJSON(
  createPlaybackIdOfStreamRequest: CreatePlaybackIdOfStreamRequest,
): string {
  return JSON.stringify(
    CreatePlaybackIdOfStreamRequest$outboundSchema.parse(
      createPlaybackIdOfStreamRequest,
    ),
  );
}

/** @internal */
export const CreatePlaybackIdOfStreamResponse$inboundSchema: z.ZodMiniType<
  CreatePlaybackIdOfStreamResponse,
  unknown
> = smartUnion([
  models.PlaybackIdSuccessResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function createPlaybackIdOfStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePlaybackIdOfStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePlaybackIdOfStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePlaybackIdOfStreamResponse' from JSON`,
  );
}
