/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateSimulcastOfStreamRequest = {
  /**
   * After creating a new live stream, FastPix assigns a unique identifier to the stream.
   */
  streamId: string;
  body: models.SimulcastRequest;
};

export type CreateSimulcastOfStreamResponse =
  | models.SimulcastResponse
  | models.DefaultError;

/** @internal */
export type CreateSimulcastOfStreamRequest$Outbound = {
  streamId: string;
  body: models.SimulcastRequest$Outbound;
};

/** @internal */
export const CreateSimulcastOfStreamRequest$outboundSchema: z.ZodMiniType<
  CreateSimulcastOfStreamRequest$Outbound,
  CreateSimulcastOfStreamRequest
> = z.object({
  streamId: z.string(),
  body: models.SimulcastRequest$outboundSchema,
});

export function createSimulcastOfStreamRequestToJSON(
  createSimulcastOfStreamRequest: CreateSimulcastOfStreamRequest,
): string {
  return JSON.stringify(
    CreateSimulcastOfStreamRequest$outboundSchema.parse(
      createSimulcastOfStreamRequest,
    ),
  );
}

/** @internal */
export const CreateSimulcastOfStreamResponse$inboundSchema: z.ZodMiniType<
  CreateSimulcastOfStreamResponse,
  unknown
> = smartUnion([
  models.SimulcastResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function createSimulcastOfStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSimulcastOfStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSimulcastOfStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSimulcastOfStreamResponse' from JSON`,
  );
}
