/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateAPlaylistResponse =
  | models.PlaylistCreatedResponse
  | models.DefaultError;

/** @internal */
export const CreateAPlaylistResponse$inboundSchema: z.ZodMiniType<
  CreateAPlaylistResponse,
  unknown
> = smartUnion([
  models.PlaylistCreatedResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function createAPlaylistResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAPlaylistResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAPlaylistResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAPlaylistResponse' from JSON`,
  );
}
