/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateSigningKeyResponse =
  | models.CreateResponse
  | models.DefaultError;

/** @internal */
export const CreateSigningKeyResponse$inboundSchema: z.ZodMiniType<
  CreateSigningKeyResponse,
  unknown
> = smartUnion([
  models.CreateResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function createSigningKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSigningKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSigningKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSigningKeyResponse' from JSON`,
  );
}
