/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeletePlaybackIdOfStreamRequest = {
  /**
   * Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
   */
  streamId: string;
  /**
   * Unique identifier for the playbackId
   */
  playbackId: string;
};

export type DeletePlaybackIdOfStreamResponse =
  | models.LiveStreamDeleteResponse
  | models.DefaultError;

/** @internal */
export type DeletePlaybackIdOfStreamRequest$Outbound = {
  streamId: string;
  playbackId: string;
};

/** @internal */
export const DeletePlaybackIdOfStreamRequest$outboundSchema: z.ZodMiniType<
  DeletePlaybackIdOfStreamRequest$Outbound,
  DeletePlaybackIdOfStreamRequest
> = z.object({
  streamId: z.string(),
  playbackId: z.string(),
});

export function deletePlaybackIdOfStreamRequestToJSON(
  deletePlaybackIdOfStreamRequest: DeletePlaybackIdOfStreamRequest,
): string {
  return JSON.stringify(
    DeletePlaybackIdOfStreamRequest$outboundSchema.parse(
      deletePlaybackIdOfStreamRequest,
    ),
  );
}

/** @internal */
export const DeletePlaybackIdOfStreamResponse$inboundSchema: z.ZodMiniType<
  DeletePlaybackIdOfStreamResponse,
  unknown
> = smartUnion([
  models.LiveStreamDeleteResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function deletePlaybackIdOfStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeletePlaybackIdOfStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePlaybackIdOfStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePlaybackIdOfStreamResponse' from JSON`,
  );
}
