/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeleteMediaPlaybackIdRequest = {
  /**
   * The unique identifier assigned to the media when created. The value must be a valid UUID.
   */
  mediaId: string;
  /**
   * Return the universal unique identifier for playbacks  which can contain a maximum of 255 characters.
   */
  playbackId: string;
};

/**
 * Deleted a Playback Id successfully
 */
export type DeleteMediaPlaybackIdResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
};

export type DeleteMediaPlaybackIdResponse =
  | DeleteMediaPlaybackIdResponseBody
  | models.DefaultError;

/** @internal */
export type DeleteMediaPlaybackIdRequest$Outbound = {
  mediaId: string;
  playbackId: string;
};

/** @internal */
export const DeleteMediaPlaybackIdRequest$outboundSchema: z.ZodMiniType<
  DeleteMediaPlaybackIdRequest$Outbound,
  DeleteMediaPlaybackIdRequest
> = z.object({
  mediaId: z.string(),
  playbackId: z.string(),
});

export function deleteMediaPlaybackIdRequestToJSON(
  deleteMediaPlaybackIdRequest: DeleteMediaPlaybackIdRequest,
): string {
  return JSON.stringify(
    DeleteMediaPlaybackIdRequest$outboundSchema.parse(
      deleteMediaPlaybackIdRequest,
    ),
  );
}

/** @internal */
export const DeleteMediaPlaybackIdResponseBody$inboundSchema: z.ZodMiniType<
  DeleteMediaPlaybackIdResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
});

export function deleteMediaPlaybackIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteMediaPlaybackIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteMediaPlaybackIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteMediaPlaybackIdResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteMediaPlaybackIdResponse$inboundSchema: z.ZodMiniType<
  DeleteMediaPlaybackIdResponse,
  unknown
> = smartUnion([
  z.lazy(() => DeleteMediaPlaybackIdResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function deleteMediaPlaybackIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteMediaPlaybackIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteMediaPlaybackIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteMediaPlaybackIdResponse' from JSON`,
  );
}
