/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeleteLiveStreamRequest = {
  /**
   * Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
   */
  streamId: string;
};

export type DeleteLiveStreamResponse =
  | models.LiveStreamDeleteResponse
  | models.DefaultError;

/** @internal */
export type DeleteLiveStreamRequest$Outbound = {
  streamId: string;
};

/** @internal */
export const DeleteLiveStreamRequest$outboundSchema: z.ZodMiniType<
  DeleteLiveStreamRequest$Outbound,
  DeleteLiveStreamRequest
> = z.object({
  streamId: z.string(),
});

export function deleteLiveStreamRequestToJSON(
  deleteLiveStreamRequest: DeleteLiveStreamRequest,
): string {
  return JSON.stringify(
    DeleteLiveStreamRequest$outboundSchema.parse(deleteLiveStreamRequest),
  );
}

/** @internal */
export const DeleteLiveStreamResponse$inboundSchema: z.ZodMiniType<
  DeleteLiveStreamResponse,
  unknown
> = smartUnion([
  models.LiveStreamDeleteResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function deleteLiveStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLiveStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLiveStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLiveStreamResponse' from JSON`,
  );
}
