/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeleteMediaFromPlaylistRequest = {
  /**
   * The unique id of the playlist you want to perform the operation on.
   */
  playlistId: string;
  body?: models.MediaIdsRequest | undefined;
};

export type DeleteMediaFromPlaylistResponse =
  | models.PlaylistByIdResponse
  | models.DefaultError;

/** @internal */
export type DeleteMediaFromPlaylistRequest$Outbound = {
  playlistId: string;
  body?: models.MediaIdsRequest$Outbound | undefined;
};

/** @internal */
export const DeleteMediaFromPlaylistRequest$outboundSchema: z.ZodMiniType<
  DeleteMediaFromPlaylistRequest$Outbound,
  DeleteMediaFromPlaylistRequest
> = z.object({
  playlistId: z.string(),
  body: z.optional(models.MediaIdsRequest$outboundSchema),
});

export function deleteMediaFromPlaylistRequestToJSON(
  deleteMediaFromPlaylistRequest: DeleteMediaFromPlaylistRequest,
): string {
  return JSON.stringify(
    DeleteMediaFromPlaylistRequest$outboundSchema.parse(
      deleteMediaFromPlaylistRequest,
    ),
  );
}

/** @internal */
export const DeleteMediaFromPlaylistResponse$inboundSchema: z.ZodMiniType<
  DeleteMediaFromPlaylistResponse,
  unknown
> = smartUnion([
  models.PlaylistByIdResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function deleteMediaFromPlaylistResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteMediaFromPlaylistResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteMediaFromPlaylistResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteMediaFromPlaylistResponse' from JSON`,
  );
}
