/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeleteSimulcastOfStreamRequest = {
  /**
   * After creating a new live stream, FastPix assigns a unique identifier to the stream.
   */
  streamId: string;
  /**
   * When you create the new simulcast, FastPix assign a universal unique identifier which can contain a maximum of 255 characters.
   */
  simulcastId: string;
};

export type DeleteSimulcastOfStreamResponse =
  | models.SimulcastdeleteResponse
  | models.DefaultError;

/** @internal */
export type DeleteSimulcastOfStreamRequest$Outbound = {
  streamId: string;
  simulcastId: string;
};

/** @internal */
export const DeleteSimulcastOfStreamRequest$outboundSchema: z.ZodMiniType<
  DeleteSimulcastOfStreamRequest$Outbound,
  DeleteSimulcastOfStreamRequest
> = z.object({
  streamId: z.string(),
  simulcastId: z.string(),
});

export function deleteSimulcastOfStreamRequestToJSON(
  deleteSimulcastOfStreamRequest: DeleteSimulcastOfStreamRequest,
): string {
  return JSON.stringify(
    DeleteSimulcastOfStreamRequest$outboundSchema.parse(
      deleteSimulcastOfStreamRequest,
    ),
  );
}

/** @internal */
export const DeleteSimulcastOfStreamResponse$inboundSchema: z.ZodMiniType<
  DeleteSimulcastOfStreamResponse,
  unknown
> = smartUnion([
  models.SimulcastdeleteResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function deleteSimulcastOfStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSimulcastOfStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSimulcastOfStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSimulcastOfStreamResponse' from JSON`,
  );
}
