/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DisableLiveStreamRequest = {
  /**
   * After creating a new live stream, FastPix assigns a unique identifier to the stream.
   */
  streamId: string;
};

export type DisableLiveStreamResponse =
  | models.LiveStreamDeleteResponse
  | models.DefaultError;

/** @internal */
export type DisableLiveStreamRequest$Outbound = {
  streamId: string;
};

/** @internal */
export const DisableLiveStreamRequest$outboundSchema: z.ZodMiniType<
  DisableLiveStreamRequest$Outbound,
  DisableLiveStreamRequest
> = z.object({
  streamId: z.string(),
});

export function disableLiveStreamRequestToJSON(
  disableLiveStreamRequest: DisableLiveStreamRequest,
): string {
  return JSON.stringify(
    DisableLiveStreamRequest$outboundSchema.parse(disableLiveStreamRequest),
  );
}

/** @internal */
export const DisableLiveStreamResponse$inboundSchema: z.ZodMiniType<
  DisableLiveStreamResponse,
  unknown
> = smartUnion([
  models.LiveStreamDeleteResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function disableLiveStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<DisableLiveStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DisableLiveStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DisableLiveStreamResponse' from JSON`,
  );
}
