/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GenerateSubtitleTrackRequest = {
  /**
   * The unique identifier assigned to the media when created. The value must be a valid UUID.
   */
  mediaId: string;
  /**
   * A universally unique identifier (UUID) assigned to the specific track for which subtitles must be generated.
   */
  trackId: string;
  body: models.TrackSubtitlesGenerateRequest;
};

/**
 * Media details updated successfully
 */
export type GenerateSubtitleTrackResponseBody = {
  /**
   * Demonstrates whether the request is successful or not.
   */
  success?: boolean | undefined;
  /**
   * Represents the response for a successfully generated subtitle track.
   */
  data?: models.GenerateTrackResponse | undefined;
};

export type GenerateSubtitleTrackResponse =
  | GenerateSubtitleTrackResponseBody
  | models.DefaultError;

/** @internal */
export type GenerateSubtitleTrackRequest$Outbound = {
  mediaId: string;
  trackId: string;
  body: models.TrackSubtitlesGenerateRequest$Outbound;
};

/** @internal */
export const GenerateSubtitleTrackRequest$outboundSchema: z.ZodMiniType<
  GenerateSubtitleTrackRequest$Outbound,
  GenerateSubtitleTrackRequest
> = z.object({
  mediaId: z.string(),
  trackId: z.string(),
  body: models.TrackSubtitlesGenerateRequest$outboundSchema,
});

export function generateSubtitleTrackRequestToJSON(
  generateSubtitleTrackRequest: GenerateSubtitleTrackRequest,
): string {
  return JSON.stringify(
    GenerateSubtitleTrackRequest$outboundSchema.parse(
      generateSubtitleTrackRequest,
    ),
  );
}

/** @internal */
export const GenerateSubtitleTrackResponseBody$inboundSchema: z.ZodMiniType<
  GenerateSubtitleTrackResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(models.GenerateTrackResponse$inboundSchema),
});

export function generateSubtitleTrackResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GenerateSubtitleTrackResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateSubtitleTrackResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateSubtitleTrackResponseBody' from JSON`,
  );
}

/** @internal */
export const GenerateSubtitleTrackResponse$inboundSchema: z.ZodMiniType<
  GenerateSubtitleTrackResponse,
  unknown
> = smartUnion([
  z.lazy(() => GenerateSubtitleTrackResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function generateSubtitleTrackResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenerateSubtitleTrackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateSubtitleTrackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateSubtitleTrackResponse' from JSON`,
  );
}
