/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAllPlaylistsRequest = {
  /**
   * The number of playlists to return (default is 10, max is 50).
   */
  limit?: number | undefined;
  /**
   * The page number to retrieve, starting from 1. Use this parameter to paginate the playlist results.
   */
  offset?: number | undefined;
};

export type GetAllPlaylistsResponse =
  | models.GetAllPlaylistsResponse
  | models.DefaultError;

/** @internal */
export type GetAllPlaylistsRequest$Outbound = {
  limit: number;
  offset: number;
};

/** @internal */
export const GetAllPlaylistsRequest$outboundSchema: z.ZodMiniType<
  GetAllPlaylistsRequest$Outbound,
  GetAllPlaylistsRequest
> = z.object({
  limit: z._default(z.int(), 10),
  offset: z._default(z.int(), 1),
});

export function getAllPlaylistsRequestToJSON(
  getAllPlaylistsRequest: GetAllPlaylistsRequest,
): string {
  return JSON.stringify(
    GetAllPlaylistsRequest$outboundSchema.parse(getAllPlaylistsRequest),
  );
}

/** @internal */
export const GetAllPlaylistsResponse$inboundSchema: z.ZodMiniType<
  GetAllPlaylistsResponse,
  unknown
> = smartUnion([
  models.GetAllPlaylistsResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function getAllPlaylistsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllPlaylistsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllPlaylistsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllPlaylistsResponse' from JSON`,
  );
}
