/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The list of value can be order in two ways DESC (Descending) or ASC (Ascending). In case not specified, by default it will be DESC.
 */
export const OrderBy = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The list of value can be order in two ways DESC (Descending) or ASC (Ascending). In case not specified, by default it will be DESC.
 */
export type OrderBy = ClosedEnum<typeof OrderBy>;

export type GetAllStreamsRequest = {
  /**
   * Limit specifies the maximum number of items to display per page.
   */
  limit?: number | undefined;
  /**
   * Offset determines the starting point for data retrieval within a paginated list.
   */
  offset?: number | undefined;
  /**
   * The list of value can be order in two ways DESC (Descending) or ASC (Ascending). In case not specified, by default it will be DESC.
   */
  orderBy?: OrderBy | undefined;
};

export type GetAllStreamsResponse =
  | models.GetStreamsResponse
  | models.DefaultError;

/** @internal */
export const OrderBy$outboundSchema: z.ZodMiniEnum<typeof OrderBy> = z.enum(
  OrderBy,
);

/** @internal */
export type GetAllStreamsRequest$Outbound = {
  limit: number;
  offset: number;
  orderBy: string;
};

/** @internal */
export const GetAllStreamsRequest$outboundSchema: z.ZodMiniType<
  GetAllStreamsRequest$Outbound,
  GetAllStreamsRequest
> = z.object({
  limit: z._default(z.int(), 10),
  offset: z._default(z.int(), 1),
  orderBy: z._default(OrderBy$outboundSchema, "desc"),
});

export function getAllStreamsRequestToJSON(
  getAllStreamsRequest: GetAllStreamsRequest,
): string {
  return JSON.stringify(
    GetAllStreamsRequest$outboundSchema.parse(getAllStreamsRequest),
  );
}

/** @internal */
export const GetAllStreamsResponse$inboundSchema: z.ZodMiniType<
  GetAllStreamsResponse,
  unknown
> = smartUnion([
  models.GetStreamsResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function getAllStreamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllStreamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllStreamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllStreamsResponse' from JSON`,
  );
}
