/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetDrmConfigurationRequest = {
  /**
   * Offset determines the starting point for data retrieval within a paginated list.
   */
  offset?: number | undefined;
  /**
   * Limit specifies the maximum number of items to display per page.
   */
  limit?: number | undefined;
};

/**
 * DRM configuration(s) retrieved successfully
 */
export type GetDrmConfigurationResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  data?: Array<models.DrmIdResponse> | undefined;
  /**
   * Pagination organizes content into pages for better readability and navigation.
   */
  pagination?: models.Pagination | undefined;
};

export type GetDrmConfigurationResponse =
  | GetDrmConfigurationResponseBody
  | models.DefaultError;

/** @internal */
export type GetDrmConfigurationRequest$Outbound = {
  offset: number;
  limit: number;
};

/** @internal */
export const GetDrmConfigurationRequest$outboundSchema: z.ZodMiniType<
  GetDrmConfigurationRequest$Outbound,
  GetDrmConfigurationRequest
> = z.object({
  offset: z._default(z.int(), 1),
  limit: z._default(z.int(), 10),
});

export function getDrmConfigurationRequestToJSON(
  getDrmConfigurationRequest: GetDrmConfigurationRequest,
): string {
  return JSON.stringify(
    GetDrmConfigurationRequest$outboundSchema.parse(getDrmConfigurationRequest),
  );
}

/** @internal */
export const GetDrmConfigurationResponseBody$inboundSchema: z.ZodMiniType<
  GetDrmConfigurationResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(models.DrmIdResponse$inboundSchema)),
  pagination: types.optional(models.Pagination$inboundSchema),
});

export function getDrmConfigurationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetDrmConfigurationResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDrmConfigurationResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDrmConfigurationResponseBody' from JSON`,
  );
}

/** @internal */
export const GetDrmConfigurationResponse$inboundSchema: z.ZodMiniType<
  GetDrmConfigurationResponse,
  unknown
> = smartUnion([
  z.lazy(() => GetDrmConfigurationResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function getDrmConfigurationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDrmConfigurationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDrmConfigurationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDrmConfigurationResponse' from JSON`,
  );
}
