/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetMediaSummaryRequest = {
  /**
   * The unique identifier assigned to the media when created. The value must be a valid UUID.
   */
  mediaId: string;
};

/**
 * Get media summary
 */
export type GetMediaSummaryResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * The summary of the particular video.
   */
  data?: string | undefined;
};

export type GetMediaSummaryResponse =
  | GetMediaSummaryResponseBody
  | models.DefaultError;

/** @internal */
export type GetMediaSummaryRequest$Outbound = {
  mediaId: string;
};

/** @internal */
export const GetMediaSummaryRequest$outboundSchema: z.ZodMiniType<
  GetMediaSummaryRequest$Outbound,
  GetMediaSummaryRequest
> = z.object({
  mediaId: z.string(),
});

export function getMediaSummaryRequestToJSON(
  getMediaSummaryRequest: GetMediaSummaryRequest,
): string {
  return JSON.stringify(
    GetMediaSummaryRequest$outboundSchema.parse(getMediaSummaryRequest),
  );
}

/** @internal */
export const GetMediaSummaryResponseBody$inboundSchema: z.ZodMiniType<
  GetMediaSummaryResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(types.string()),
});

export function getMediaSummaryResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetMediaSummaryResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMediaSummaryResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMediaSummaryResponseBody' from JSON`,
  );
}

/** @internal */
export const GetMediaSummaryResponse$inboundSchema: z.ZodMiniType<
  GetMediaSummaryResponse,
  unknown
> = smartUnion([
  z.lazy(() => GetMediaSummaryResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function getMediaSummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetMediaSummaryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMediaSummaryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMediaSummaryResponse' from JSON`,
  );
}
