/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetPlaybackIdRequest = {
  mediaId: string;
  playbackId: string;
};

/**
 * The access policy set for the playback ID.
 */
export const GetPlaybackIdAccessPolicy = {
  Public: "public",
  Private: "private",
  Drm: "drm",
} as const;
/**
 * The access policy set for the playback ID.
 */
export type GetPlaybackIdAccessPolicy = OpenEnum<
  typeof GetPlaybackIdAccessPolicy
>;

export const GetPlaybackIdDomainsDefaultPolicy = {
  Allow: "allow",
  Deny: "deny",
} as const;
export type GetPlaybackIdDomainsDefaultPolicy = OpenEnum<
  typeof GetPlaybackIdDomainsDefaultPolicy
>;

export type GetPlaybackIdDomains = {
  defaultPolicy?: GetPlaybackIdDomainsDefaultPolicy | undefined;
  allow?: Array<string> | undefined;
  deny?: Array<string> | undefined;
};

export const GetPlaybackIdUserAgentsDefaultPolicy = {
  Allow: "allow",
  Deny: "deny",
} as const;
export type GetPlaybackIdUserAgentsDefaultPolicy = OpenEnum<
  typeof GetPlaybackIdUserAgentsDefaultPolicy
>;

export type GetPlaybackIdUserAgents = {
  defaultPolicy?: GetPlaybackIdUserAgentsDefaultPolicy | undefined;
  allow?: Array<string> | undefined;
  deny?: Array<string> | undefined;
};

/**
 * Restrictions applied to this playback ID.
 */
export type GetPlaybackIdAccessRestrictions = {
  domains?: GetPlaybackIdDomains | undefined;
  userAgents?: GetPlaybackIdUserAgents | undefined;
};

export type GetPlaybackIdData = {
  /**
   * Unique identifier of the playback ID.
   */
  id?: string | undefined;
  /**
   * The access policy set for the playback ID.
   */
  accessPolicy?: GetPlaybackIdAccessPolicy | undefined;
  /**
   * Restrictions applied to this playback ID.
   */
  accessRestrictions?: GetPlaybackIdAccessRestrictions | undefined;
};

/**
 * Successfully retrieved playback ID details
 */
export type GetPlaybackIdResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  data?: GetPlaybackIdData | undefined;
};

export type GetPlaybackIdResponse =
  | GetPlaybackIdResponseBody
  | models.DefaultError;

/** @internal */
export type GetPlaybackIdRequest$Outbound = {
  mediaId: string;
  playbackId: string;
};

/** @internal */
export const GetPlaybackIdRequest$outboundSchema: z.ZodMiniType<
  GetPlaybackIdRequest$Outbound,
  GetPlaybackIdRequest
> = z.object({
  mediaId: z.string(),
  playbackId: z.string(),
});

export function getPlaybackIdRequestToJSON(
  getPlaybackIdRequest: GetPlaybackIdRequest,
): string {
  return JSON.stringify(
    GetPlaybackIdRequest$outboundSchema.parse(getPlaybackIdRequest),
  );
}

/** @internal */
export const GetPlaybackIdAccessPolicy$inboundSchema: z.ZodMiniType<
  GetPlaybackIdAccessPolicy,
  unknown
> = openEnums.inboundSchema(GetPlaybackIdAccessPolicy);

/** @internal */
export const GetPlaybackIdDomainsDefaultPolicy$inboundSchema: z.ZodMiniType<
  GetPlaybackIdDomainsDefaultPolicy,
  unknown
> = openEnums.inboundSchema(GetPlaybackIdDomainsDefaultPolicy);

/** @internal */
export const GetPlaybackIdDomains$inboundSchema: z.ZodMiniType<
  GetPlaybackIdDomains,
  unknown
> = z.object({
  defaultPolicy: types.optional(
    GetPlaybackIdDomainsDefaultPolicy$inboundSchema,
  ),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function getPlaybackIdDomainsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaybackIdDomains, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaybackIdDomains$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaybackIdDomains' from JSON`,
  );
}

/** @internal */
export const GetPlaybackIdUserAgentsDefaultPolicy$inboundSchema: z.ZodMiniType<
  GetPlaybackIdUserAgentsDefaultPolicy,
  unknown
> = openEnums.inboundSchema(GetPlaybackIdUserAgentsDefaultPolicy);

/** @internal */
export const GetPlaybackIdUserAgents$inboundSchema: z.ZodMiniType<
  GetPlaybackIdUserAgents,
  unknown
> = z.object({
  defaultPolicy: types.optional(
    GetPlaybackIdUserAgentsDefaultPolicy$inboundSchema,
  ),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function getPlaybackIdUserAgentsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaybackIdUserAgents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaybackIdUserAgents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaybackIdUserAgents' from JSON`,
  );
}

/** @internal */
export const GetPlaybackIdAccessRestrictions$inboundSchema: z.ZodMiniType<
  GetPlaybackIdAccessRestrictions,
  unknown
> = z.object({
  domains: types.optional(z.lazy(() => GetPlaybackIdDomains$inboundSchema)),
  userAgents: types.optional(
    z.lazy(() => GetPlaybackIdUserAgents$inboundSchema),
  ),
});

export function getPlaybackIdAccessRestrictionsFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaybackIdAccessRestrictions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaybackIdAccessRestrictions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaybackIdAccessRestrictions' from JSON`,
  );
}

/** @internal */
export const GetPlaybackIdData$inboundSchema: z.ZodMiniType<
  GetPlaybackIdData,
  unknown
> = z.object({
  id: types.optional(types.string()),
  accessPolicy: types.optional(GetPlaybackIdAccessPolicy$inboundSchema),
  accessRestrictions: types.optional(
    z.lazy(() => GetPlaybackIdAccessRestrictions$inboundSchema),
  ),
});

export function getPlaybackIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaybackIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaybackIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaybackIdData' from JSON`,
  );
}

/** @internal */
export const GetPlaybackIdResponseBody$inboundSchema: z.ZodMiniType<
  GetPlaybackIdResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.lazy(() => GetPlaybackIdData$inboundSchema)),
});

export function getPlaybackIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaybackIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaybackIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaybackIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetPlaybackIdResponse$inboundSchema: z.ZodMiniType<
  GetPlaybackIdResponse,
  unknown
> = smartUnion([
  z.lazy(() => GetPlaybackIdResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function getPlaybackIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlaybackIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlaybackIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlaybackIdResponse' from JSON`,
  );
}
