/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetVideoViewDetailsRequest = {
  /**
   * Pass View Id
   */
  viewId: string;
};

/**
 * Get a video view by id
 */
export type GetVideoViewDetailsResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * Displays the result of the request.
   */
  data?: models.Views | undefined;
};

export type GetVideoViewDetailsResponse =
  | GetVideoViewDetailsResponseBody
  | models.DefaultError;

/** @internal */
export type GetVideoViewDetailsRequest$Outbound = {
  viewId: string;
};

/** @internal */
export const GetVideoViewDetailsRequest$outboundSchema: z.ZodMiniType<
  GetVideoViewDetailsRequest$Outbound,
  GetVideoViewDetailsRequest
> = z.object({
  viewId: z.string(),
});

export function getVideoViewDetailsRequestToJSON(
  getVideoViewDetailsRequest: GetVideoViewDetailsRequest,
): string {
  return JSON.stringify(
    GetVideoViewDetailsRequest$outboundSchema.parse(getVideoViewDetailsRequest),
  );
}

/** @internal */
export const GetVideoViewDetailsResponseBody$inboundSchema: z.ZodMiniType<
  GetVideoViewDetailsResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(models.Views$inboundSchema),
});

export function getVideoViewDetailsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetVideoViewDetailsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVideoViewDetailsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVideoViewDetailsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetVideoViewDetailsResponse$inboundSchema: z.ZodMiniType<
  GetVideoViewDetailsResponse,
  unknown
> = smartUnion([
  z.lazy(() => GetVideoViewDetailsResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function getVideoViewDetailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetVideoViewDetailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVideoViewDetailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVideoViewDetailsResponse' from JSON`,
  );
}
