/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListMediaRequest = {
  /**
   * Limit specifies the maximum number of items to display per page.
   */
  limit?: number | undefined;
  /**
   * Offset determines the starting point for data retrieval within a paginated list.
   */
  offset?: number | undefined;
  /**
   * The values in the list can be arranged in two ways: DESC (Descending) or ASC (Ascending).
   */
  orderBy?: models.SortOrder | undefined;
};

/**
 * List of video media
 */
export type ListMediaResponseBody = {
  /**
   * Demonstrates whether the request is successful or not.
   */
  success?: boolean | undefined;
  /**
   * Displays the result of the request.
   */
  data?: Array<models.GetAllMediaResponse> | undefined;
  /**
   * Pagination organizes content into pages for better readability and navigation.
   */
  pagination?: models.Pagination | undefined;
};

export type ListMediaResponse = ListMediaResponseBody | models.DefaultError;

/** @internal */
export type ListMediaRequest$Outbound = {
  limit: number;
  offset: number;
  orderBy: string;
};

/** @internal */
export const ListMediaRequest$outboundSchema: z.ZodMiniType<
  ListMediaRequest$Outbound,
  ListMediaRequest
> = z.object({
  limit: z._default(z.int(), 10),
  offset: z._default(z.int(), 1),
  orderBy: z._default(models.SortOrder$outboundSchema, "desc"),
});

export function listMediaRequestToJSON(
  listMediaRequest: ListMediaRequest,
): string {
  return JSON.stringify(
    ListMediaRequest$outboundSchema.parse(listMediaRequest),
  );
}

/** @internal */
export const ListMediaResponseBody$inboundSchema: z.ZodMiniType<
  ListMediaResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(models.GetAllMediaResponse$inboundSchema)),
  pagination: types.optional(models.Pagination$inboundSchema),
});

export function listMediaResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListMediaResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMediaResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMediaResponseBody' from JSON`,
  );
}

/** @internal */
export const ListMediaResponse$inboundSchema: z.ZodMiniType<
  ListMediaResponse,
  unknown
> = smartUnion([
  z.lazy(() => ListMediaResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function listMediaResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMediaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMediaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMediaResponse' from JSON`,
  );
}
