/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Get the list of Views
 */
export type ListDimensionsResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * The endpoint retrieves a comprehensive list of dimensions
   */
  data?: Array<string> | undefined;
};

export type ListDimensionsResponse =
  | ListDimensionsResponseBody
  | models.DefaultError;

/** @internal */
export const ListDimensionsResponseBody$inboundSchema: z.ZodMiniType<
  ListDimensionsResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(types.string())),
});

export function listDimensionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListDimensionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDimensionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDimensionsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListDimensionsResponse$inboundSchema: z.ZodMiniType<
  ListDimensionsResponse,
  unknown
> = smartUnion([
  z.lazy(() => ListDimensionsResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function listDimensionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDimensionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDimensionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDimensionsResponse' from JSON`,
  );
}
