/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
 *
 * @remarks
 *
 * **Accepted formats are:**
 *
 * array of epoch timestamps for example
 * `timespan[]=1498867200&timespan[]=1498953600`
 *
 * duration string for example
 * `timespan[]=24:hours` or `timespan[]=7:days`
 */
export const ListVideoViewsTimespan = {
  Sixtyminutes: "60:minutes",
  Sixhours: "6:hours",
  TwentyFourhours: "24:hours",
  Threedays: "3:days",
  Sevendays: "7:days",
  Thirtydays: "30:days",
} as const;
/**
 * This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
 *
 * @remarks
 *
 * **Accepted formats are:**
 *
 * array of epoch timestamps for example
 * `timespan[]=1498867200&timespan[]=1498953600`
 *
 * duration string for example
 * `timespan[]=24:hours` or `timespan[]=7:days`
 */
export type ListVideoViewsTimespan = ClosedEnum<typeof ListVideoViewsTimespan>;

export type ListVideoViewsRequest = {
  /**
   * This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
   *
   * @remarks
   *
   * **Accepted formats are:**
   *
   * array of epoch timestamps for example
   * `timespan[]=1498867200&timespan[]=1498953600`
   *
   * duration string for example
   * `timespan[]=24:hours` or `timespan[]=7:days`
   */
  timespan?: ListVideoViewsTimespan | undefined;
  /**
   * Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass "!" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
   *
   * @remarks
   * Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]
   */
  filterby?: string | undefined;
  /**
   * Pass the limit to display only the rows specified by the value.
   *
   * @remarks
   */
  limit?: number | undefined;
  /**
   * Pass the offset value to indicate the page number.
   *
   * @remarks
   */
  offset?: number | undefined;
  /**
   * Pass the viewer_id to filter the list of views. This value can be manually set during integration or generated by FastPix. When set manually it can be a string of aplha numeric values of any length.
   *
   * @remarks
   */
  viewerId?: string | undefined;
  /**
   * Pass the error code to filter the list of views. The possible values of error code can be fetched from list of errors end point.
   *
   * @remarks
   */
  errorCode?: string | null | undefined;
  /**
   * Pass this value to sort the view list by.
   *
   * @remarks
   */
  orderBy?: string | undefined;
  /**
   * The order direction to sort the view list by.
   *
   * @remarks
   */
  sortOrder?: string | undefined;
};

/**
 * Get the list of Views
 */
export type ListVideoViewsResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * Displays the result of the request.
   */
  data?: Array<models.ViewsList> | undefined;
  /**
   * Pagination organizes content into pages for better readability and navigation.
   */
  pagination?: models.DataPagination | undefined;
  /**
   * The timespan from and to details displayed in the form of unix epoch timestamps.
   *
   * @remarks
   */
  timespan?: Array<number> | undefined;
};

export type ListVideoViewsResponse =
  | ListVideoViewsResponseBody
  | models.DefaultError;

/** @internal */
export const ListVideoViewsTimespan$outboundSchema: z.ZodMiniEnum<
  typeof ListVideoViewsTimespan
> = z.enum(ListVideoViewsTimespan);

/** @internal */
export type ListVideoViewsRequest$Outbound = {
  "timespan[]"?: string | undefined;
  "filterby[]"?: string | undefined;
  limit: number;
  offset: number;
  viewerId?: string | undefined;
  errorCode?: string | null | undefined;
  orderBy: string;
  sortOrder: string;
};

/** @internal */
export const ListVideoViewsRequest$outboundSchema: z.ZodMiniType<
  ListVideoViewsRequest$Outbound,
  ListVideoViewsRequest
> = z.pipe(
  z.object({
    timespan: z.optional(ListVideoViewsTimespan$outboundSchema),
    filterby: z.optional(z.string()),
    limit: z._default(z.int(), 10),
    offset: z._default(z.int(), 1),
    viewerId: z.optional(z.string()),
    errorCode: z.optional(z.nullable(z.string())),
    orderBy: z._default(z.string(), "view_end"),
    sortOrder: z._default(z.string(), "asc"),
  }),
  z.transform((v) => {
    return remap$(v, {
      timespan: "timespan[]",
      filterby: "filterby[]",
    });
  }),
);

export function listVideoViewsRequestToJSON(
  listVideoViewsRequest: ListVideoViewsRequest,
): string {
  return JSON.stringify(
    ListVideoViewsRequest$outboundSchema.parse(listVideoViewsRequest),
  );
}

/** @internal */
export const ListVideoViewsResponseBody$inboundSchema: z.ZodMiniType<
  ListVideoViewsResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(models.ViewsList$inboundSchema)),
  pagination: types.optional(models.DataPagination$inboundSchema),
  timespan: types.optional(z.array(types.number())),
});

export function listVideoViewsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListVideoViewsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListVideoViewsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListVideoViewsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListVideoViewsResponse$inboundSchema: z.ZodMiniType<
  ListVideoViewsResponse,
  unknown
> = smartUnion([
  z.lazy(() => ListVideoViewsResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function listVideoViewsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListVideoViewsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListVideoViewsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListVideoViewsResponse' from JSON`,
  );
}
