/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
 *
 * @remarks
 *
 * **Accepted formats are:**
 *
 * array of epoch timestamps for example
 * `timespan[]=1498867200&timespan[]=1498953600`
 *
 * duration string for example
 * `timespan[]=24:hours` or `timespan[]=7:days`
 */
export const ListByTopContentTimespan = {
  Sixtyminutes: "60:minutes",
  Sixhours: "6:hours",
  TwentyFourhours: "24:hours",
  Threedays: "3:days",
  Sevendays: "7:days",
  Thirtydays: "30:days",
} as const;
/**
 * This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
 *
 * @remarks
 *
 * **Accepted formats are:**
 *
 * array of epoch timestamps for example
 * `timespan[]=1498867200&timespan[]=1498953600`
 *
 * duration string for example
 * `timespan[]=24:hours` or `timespan[]=7:days`
 */
export type ListByTopContentTimespan = ClosedEnum<
  typeof ListByTopContentTimespan
>;

export type ListByTopContentRequest = {
  /**
   * This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
   *
   * @remarks
   *
   * **Accepted formats are:**
   *
   * array of epoch timestamps for example
   * `timespan[]=1498867200&timespan[]=1498953600`
   *
   * duration string for example
   * `timespan[]=24:hours` or `timespan[]=7:days`
   */
  timespan?: ListByTopContentTimespan | undefined;
  /**
   * Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass "!" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
   *
   * @remarks
   * Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]
   */
  filterby?: string | undefined;
  /**
   * Pass the limit to display only the rows specified by the value.
   *
   * @remarks
   */
  limit?: number | undefined;
};

/**
 * Get the list of Views
 */
export type ListByTopContentResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * Displays the result of the request.
   */
  data?: Array<models.ViewsByTopContentDetails> | undefined;
  /**
   * The timespan from and to details displayed in the form of unix epoch timestamps.
   *
   * @remarks
   */
  timespan?: Array<number> | undefined;
};

export type ListByTopContentResponse =
  | ListByTopContentResponseBody
  | models.DefaultError;

/** @internal */
export const ListByTopContentTimespan$outboundSchema: z.ZodMiniEnum<
  typeof ListByTopContentTimespan
> = z.enum(ListByTopContentTimespan);

/** @internal */
export type ListByTopContentRequest$Outbound = {
  "timespan[]"?: string | undefined;
  "filterby[]"?: string | undefined;
  limit: number;
};

/** @internal */
export const ListByTopContentRequest$outboundSchema: z.ZodMiniType<
  ListByTopContentRequest$Outbound,
  ListByTopContentRequest
> = z.pipe(
  z.object({
    timespan: z.optional(ListByTopContentTimespan$outboundSchema),
    filterby: z.optional(z.string()),
    limit: z._default(z.int(), 10),
  }),
  z.transform((v) => {
    return remap$(v, {
      timespan: "timespan[]",
      filterby: "filterby[]",
    });
  }),
);

export function listByTopContentRequestToJSON(
  listByTopContentRequest: ListByTopContentRequest,
): string {
  return JSON.stringify(
    ListByTopContentRequest$outboundSchema.parse(listByTopContentRequest),
  );
}

/** @internal */
export const ListByTopContentResponseBody$inboundSchema: z.ZodMiniType<
  ListByTopContentResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(models.ViewsByTopContentDetails$inboundSchema)),
  timespan: types.optional(z.array(types.number())),
});

export function listByTopContentResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListByTopContentResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListByTopContentResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListByTopContentResponseBody' from JSON`,
  );
}

/** @internal */
export const ListByTopContentResponse$inboundSchema: z.ZodMiniType<
  ListByTopContentResponse,
  unknown
> = smartUnion([
  z.lazy(() => ListByTopContentResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function listByTopContentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListByTopContentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListByTopContentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListByTopContentResponse' from JSON`,
  );
}
