/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListSigningKeysRequest = {
  /**
   * Limit specifies the maximum number of items to display per page.
   */
  limit?: number | undefined;
  /**
   * It is used for pagination, indicating the starting point for fetching data.
   */
  offset?: number | undefined;
};

export type ListSigningKeysResponse =
  | models.GetAllSigningKeysResponse
  | models.DefaultError;

/** @internal */
export type ListSigningKeysRequest$Outbound = {
  limit: number;
  offset: number;
};

/** @internal */
export const ListSigningKeysRequest$outboundSchema: z.ZodMiniType<
  ListSigningKeysRequest$Outbound,
  ListSigningKeysRequest
> = z.object({
  limit: z._default(z.number(), 10),
  offset: z._default(z.number(), 1),
});

export function listSigningKeysRequestToJSON(
  listSigningKeysRequest: ListSigningKeysRequest,
): string {
  return JSON.stringify(
    ListSigningKeysRequest$outboundSchema.parse(listSigningKeysRequest),
  );
}

/** @internal */
export const ListSigningKeysResponse$inboundSchema: z.ZodMiniType<
  ListSigningKeysResponse,
  unknown
> = smartUnion([
  models.GetAllSigningKeysResponse$inboundSchema,
  models.DefaultError$inboundSchema,
]);

export function listSigningKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSigningKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSigningKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSigningKeysResponse' from JSON`,
  );
}
