/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Determines the type of MP4 support for the media. - **none**: Disables MP4 support. - **capped_4k**: Enables MP4 downloads with resolutions up to 4K. - **audioOnly**: Provides an MP4 stream containing only the audio. - **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.
 *
 * @remarks
 */
export const UpdatedMp4SupportMp4Support = {
  None: "none",
  Capped4k: "capped_4k",
  AudioOnly: "audioOnly",
  AudioOnlyCapped4k: "audioOnly,capped_4k",
} as const;
/**
 * Determines the type of MP4 support for the media. - **none**: Disables MP4 support. - **capped_4k**: Enables MP4 downloads with resolutions up to 4K. - **audioOnly**: Provides an MP4 stream containing only the audio. - **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.
 *
 * @remarks
 */
export type UpdatedMp4SupportMp4Support = ClosedEnum<
  typeof UpdatedMp4SupportMp4Support
>;

export type UpdatedMp4SupportRequestBody = {
  /**
   * Determines the type of MP4 support for the media. - **none**: Disables MP4 support. - **capped_4k**: Enables MP4 downloads with resolutions up to 4K. - **audioOnly**: Provides an MP4 stream containing only the audio. - **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.
   *
   * @remarks
   */
  mp4Support?: UpdatedMp4SupportMp4Support | undefined;
};

export type UpdatedMp4SupportRequest = {
  /**
   * The unique identifier assigned to the media when created. The value must be a valid UUID.
   *
   * @remarks
   */
  mediaId: string;
  body: UpdatedMp4SupportRequestBody;
};

/**
 * Media details updated successfully
 */
export type UpdatedMp4SupportResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  data?: models.Media | undefined;
};

export type UpdatedMp4SupportResponse =
  | UpdatedMp4SupportResponseBody
  | models.DefaultError;

/** @internal */
export const UpdatedMp4SupportMp4Support$outboundSchema: z.ZodMiniEnum<
  typeof UpdatedMp4SupportMp4Support
> = z.enum(UpdatedMp4SupportMp4Support);

/** @internal */
export type UpdatedMp4SupportRequestBody$Outbound = {
  mp4Support: string;
};

/** @internal */
export const UpdatedMp4SupportRequestBody$outboundSchema: z.ZodMiniType<
  UpdatedMp4SupportRequestBody$Outbound,
  UpdatedMp4SupportRequestBody
> = z.object({
  mp4Support: z._default(
    UpdatedMp4SupportMp4Support$outboundSchema,
    "capped_4k",
  ),
});

export function updatedMp4SupportRequestBodyToJSON(
  updatedMp4SupportRequestBody: UpdatedMp4SupportRequestBody,
): string {
  return JSON.stringify(
    UpdatedMp4SupportRequestBody$outboundSchema.parse(
      updatedMp4SupportRequestBody,
    ),
  );
}

/** @internal */
export type UpdatedMp4SupportRequest$Outbound = {
  mediaId: string;
  body: UpdatedMp4SupportRequestBody$Outbound;
};

/** @internal */
export const UpdatedMp4SupportRequest$outboundSchema: z.ZodMiniType<
  UpdatedMp4SupportRequest$Outbound,
  UpdatedMp4SupportRequest
> = z.object({
  mediaId: z.string(),
  body: z.lazy(() => UpdatedMp4SupportRequestBody$outboundSchema),
});

export function updatedMp4SupportRequestToJSON(
  updatedMp4SupportRequest: UpdatedMp4SupportRequest,
): string {
  return JSON.stringify(
    UpdatedMp4SupportRequest$outboundSchema.parse(updatedMp4SupportRequest),
  );
}

/** @internal */
export const UpdatedMp4SupportResponseBody$inboundSchema: z.ZodMiniType<
  UpdatedMp4SupportResponseBody,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(models.Media$inboundSchema),
});

export function updatedMp4SupportResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdatedMp4SupportResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatedMp4SupportResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatedMp4SupportResponseBody' from JSON`,
  );
}

/** @internal */
export const UpdatedMp4SupportResponse$inboundSchema: z.ZodMiniType<
  UpdatedMp4SupportResponse,
  unknown
> = smartUnion([
  z.lazy(() => UpdatedMp4SupportResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function updatedMp4SupportResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatedMp4SupportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatedMp4SupportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatedMp4SupportResponse' from JSON`,
  );
}
