/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The default behavior when a user-agent is not listed in `allow` or `deny`.
 */
export const UpdateUserAgentRestrictionsDefaultPolicy = {
  Allow: "allow",
  Deny: "deny",
} as const;
/**
 * The default behavior when a user-agent is not listed in `allow` or `deny`.
 */
export type UpdateUserAgentRestrictionsDefaultPolicy = ClosedEnum<
  typeof UpdateUserAgentRestrictionsDefaultPolicy
>;

export type UpdateUserAgentRestrictionsRequestBody = {
  /**
   * The default behavior when a user-agent is not listed in `allow` or `deny`.
   */
  defaultPolicy?: UpdateUserAgentRestrictionsDefaultPolicy | undefined;
  /**
   * List of user-agent substrings explicitly allowed.
   */
  allow?: Array<string> | undefined;
  /**
   * List of user-agent substrings explicitly denied.
   */
  deny?: Array<string> | undefined;
};

export type UpdateUserAgentRestrictionsRequest = {
  mediaId: string;
  playbackId: string;
  body: UpdateUserAgentRestrictionsRequestBody;
};

export type UpdateUserAgentRestrictionsData = {
  /**
   * Specifies the default behavior for user agents not listed in the allow or deny lists.
   */
  defaultPolicy?: string | undefined;
  /**
   * List of user-agent substrings explicitly allowed.
   */
  allow?: Array<string> | undefined;
  /**
   * List of user-agent substrings explicitly denied.
   */
  deny?: Array<string> | undefined;
};

/**
 * Successfully updated user-agent restrictions
 */
export type UpdateUserAgentRestrictionsResponseBody = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  data?: UpdateUserAgentRestrictionsData | undefined;
};

export type UpdateUserAgentRestrictionsResponse =
  | UpdateUserAgentRestrictionsResponseBody
  | models.DefaultError;

/** @internal */
export const UpdateUserAgentRestrictionsDefaultPolicy$outboundSchema:
  z.ZodMiniEnum<typeof UpdateUserAgentRestrictionsDefaultPolicy> = z.enum(
    UpdateUserAgentRestrictionsDefaultPolicy,
  );

/** @internal */
export type UpdateUserAgentRestrictionsRequestBody$Outbound = {
  defaultPolicy: string;
  allow?: Array<string> | undefined;
  deny?: Array<string> | undefined;
};

/** @internal */
export const UpdateUserAgentRestrictionsRequestBody$outboundSchema:
  z.ZodMiniType<
    UpdateUserAgentRestrictionsRequestBody$Outbound,
    UpdateUserAgentRestrictionsRequestBody
  > = z.object({
    defaultPolicy: z._default(
      UpdateUserAgentRestrictionsDefaultPolicy$outboundSchema,
      "allow",
    ),
    allow: z.optional(z.array(z.string())),
    deny: z.optional(z.array(z.string())),
  });

export function updateUserAgentRestrictionsRequestBodyToJSON(
  updateUserAgentRestrictionsRequestBody:
    UpdateUserAgentRestrictionsRequestBody,
): string {
  return JSON.stringify(
    UpdateUserAgentRestrictionsRequestBody$outboundSchema.parse(
      updateUserAgentRestrictionsRequestBody,
    ),
  );
}

/** @internal */
export type UpdateUserAgentRestrictionsRequest$Outbound = {
  mediaId: string;
  playbackId: string;
  body: UpdateUserAgentRestrictionsRequestBody$Outbound;
};

/** @internal */
export const UpdateUserAgentRestrictionsRequest$outboundSchema: z.ZodMiniType<
  UpdateUserAgentRestrictionsRequest$Outbound,
  UpdateUserAgentRestrictionsRequest
> = z.object({
  mediaId: z.string(),
  playbackId: z.string(),
  body: z.lazy(() => UpdateUserAgentRestrictionsRequestBody$outboundSchema),
});

export function updateUserAgentRestrictionsRequestToJSON(
  updateUserAgentRestrictionsRequest: UpdateUserAgentRestrictionsRequest,
): string {
  return JSON.stringify(
    UpdateUserAgentRestrictionsRequest$outboundSchema.parse(
      updateUserAgentRestrictionsRequest,
    ),
  );
}

/** @internal */
export const UpdateUserAgentRestrictionsData$inboundSchema: z.ZodMiniType<
  UpdateUserAgentRestrictionsData,
  unknown
> = z.object({
  defaultPolicy: types.optional(types.string()),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function updateUserAgentRestrictionsDataFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUserAgentRestrictionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUserAgentRestrictionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUserAgentRestrictionsData' from JSON`,
  );
}

/** @internal */
export const UpdateUserAgentRestrictionsResponseBody$inboundSchema:
  z.ZodMiniType<UpdateUserAgentRestrictionsResponseBody, unknown> = z.object({
    success: types.optional(types.boolean()),
    data: types.optional(
      z.lazy(() => UpdateUserAgentRestrictionsData$inboundSchema),
    ),
  });

export function updateUserAgentRestrictionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateUserAgentRestrictionsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateUserAgentRestrictionsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateUserAgentRestrictionsResponseBody' from JSON`,
  );
}

/** @internal */
export const UpdateUserAgentRestrictionsResponse$inboundSchema: z.ZodMiniType<
  UpdateUserAgentRestrictionsResponse,
  unknown
> = smartUnion([
  z.lazy(() => UpdateUserAgentRestrictionsResponseBody$inboundSchema),
  models.DefaultError$inboundSchema,
]);

export function updateUserAgentRestrictionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUserAgentRestrictionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateUserAgentRestrictionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUserAgentRestrictionsResponse' from JSON`,
  );
}
