/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import {
  DomainRestrictions,
  DomainRestrictions$Outbound,
  DomainRestrictions$outboundSchema,
} from "./domainrestrictions.js";
import {
  UserAgentRestrictions,
  UserAgentRestrictions$Outbound,
  UserAgentRestrictions$outboundSchema,
} from "./useragentrestrictions.js";

/**
 * Access control restrictions applied to a playback ID.
 */
export type AccessRestrictions = {
  /**
   * Restrictions based on the originating domain of a request
   */
  domains?: DomainRestrictions | undefined;
  /**
   * Restrictions based on the user agent
   */
  userAgents?: UserAgentRestrictions | undefined;
};

/** @internal */
export type AccessRestrictions$Outbound = {
  domains?: DomainRestrictions$Outbound | undefined;
  userAgents?: UserAgentRestrictions$Outbound | undefined;
};

/** @internal */
export const AccessRestrictions$outboundSchema: z.ZodMiniType<
  AccessRestrictions$Outbound,
  AccessRestrictions
> = z.object({
  domains: z.optional(z.lazy(() => DomainRestrictions$outboundSchema)),
  userAgents: z.optional(z.lazy(() => UserAgentRestrictions$outboundSchema)),
});

export function accessRestrictionsToJSON(
  accessRestrictions: AccessRestrictions,
): string {
  return JSON.stringify(
    AccessRestrictions$outboundSchema.parse(accessRestrictions),
  );
}
