/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BrowserNameDimensiondetails = {
  /**
   * The specific metric value calculated based on the applied filters.
   */
  value?: string | undefined;
  /**
   * The count of unique viewers who interacted with the content.
   */
  uniqueCount?: number | undefined;
  /**
   * The count of viewers.
   */
  count?: number | undefined;
};

/** @internal */
export const BrowserNameDimensiondetails$inboundSchema: z.ZodMiniType<
  BrowserNameDimensiondetails,
  unknown
> = z.object({
  value: types.optional(types.string()),
  uniqueCount: types.optional(types.number()),
  count: types.optional(types.number()),
});

export function browserNameDimensiondetailsFromJSON(
  jsonString: string,
): SafeParseResult<BrowserNameDimensiondetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BrowserNameDimensiondetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BrowserNameDimensiondetails' from JSON`,
  );
}
