/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChaptersResponse = {
  mediaId?: string | undefined;
  isChaptersEnabled?: boolean | undefined;
};

/** @internal */
export const ChaptersResponse$inboundSchema: z.ZodMiniType<
  ChaptersResponse,
  unknown
> = z.object({
  mediaId: types.optional(types.string()),
  isChaptersEnabled: types.optional(types.boolean()),
});

export function chaptersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChaptersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChaptersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChaptersResponse' from JSON`,
  );
}
