/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CreateMediaResponse,
  CreateMediaResponse$inboundSchema,
} from "./createmediaresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreateMediaSuccessResponse = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  data?: CreateMediaResponse | undefined;
};

/** @internal */
export const CreateMediaSuccessResponse$inboundSchema: z.ZodMiniType<
  CreateMediaSuccessResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(CreateMediaResponse$inboundSchema),
});

export function createMediaSuccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateMediaSuccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMediaSuccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMediaSuccessResponse' from JSON`,
  );
}
