/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AccessPolicy, AccessPolicy$inboundSchema } from "./accesspolicy.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PolicyAction, PolicyAction$inboundSchema } from "./policyaction.js";

/**
 * Restrictions based on the originating domain of a request (for example, whether requests from certain websites should be allowed or blocked).
 */
export type CreatePlaybackIdDomains = {
  /**
   * Policy action type
   */
  defaultPolicy?: PolicyAction | undefined;
  /**
   * A list of domains that are explicitly allowed access.
   */
  allow?: Array<string> | undefined;
  /**
   * A list of domains that are explicitly blocked from accessing the resource.
   */
  deny?: Array<string> | undefined;
};

/**
 * Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
 */
export type CreatePlaybackIdUserAgents = {
  /**
   * Policy action type
   */
  defaultPolicy?: PolicyAction | undefined;
  /**
   * A list of specific user agents that are allowed to access the resource.
   */
  allow?: Array<string> | undefined;
  /**
   * A list of specific user agents that are blocked.
   */
  deny?: Array<string> | undefined;
};

/**
 * Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
 */
export type CreatePlaybackIdAccessRestrictions = {
  /**
   * Restrictions based on the originating domain of a request (for example, whether requests from certain websites should be allowed or blocked).
   */
  domains?: CreatePlaybackIdDomains | undefined;
  /**
   * Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
   */
  userAgents?: CreatePlaybackIdUserAgents | undefined;
};

/**
 * The maximum resolution for the playback ID.
 */
export const Resolution = {
  FourHundredAndEightyp: "480p",
  SevenHundredAndTwentyp: "720p",
  OneThousandAndEightyp: "1080p",
  OneThousandFourHundredAndFortyp: "1440p",
  TwoThousandOneHundredAndSixtyp: "2160p",
} as const;
/**
 * The maximum resolution for the playback ID.
 */
export type Resolution = OpenEnum<typeof Resolution>;

/**
 * A collection of Playback ID objects utilized for crafting HLS playback urls.
 */
export type CreatePlaybackId = {
  /**
   * A unique identifier is generated by FastPix for the playbacks.
   */
  id?: string | undefined;
  /**
   * Access policy for media content
   */
  accessPolicy?: AccessPolicy | undefined;
  /**
   * Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
   */
  accessRestrictions?: CreatePlaybackIdAccessRestrictions | undefined;
  /**
   * The maximum resolution for the playback ID.
   */
  resolution?: Resolution | undefined;
};

/** @internal */
export const CreatePlaybackIdDomains$inboundSchema: z.ZodMiniType<
  CreatePlaybackIdDomains,
  unknown
> = z.object({
  defaultPolicy: types.optional(PolicyAction$inboundSchema),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function createPlaybackIdDomainsFromJSON(
  jsonString: string,
): SafeParseResult<CreatePlaybackIdDomains, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePlaybackIdDomains$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePlaybackIdDomains' from JSON`,
  );
}

/** @internal */
export const CreatePlaybackIdUserAgents$inboundSchema: z.ZodMiniType<
  CreatePlaybackIdUserAgents,
  unknown
> = z.object({
  defaultPolicy: types.optional(PolicyAction$inboundSchema),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function createPlaybackIdUserAgentsFromJSON(
  jsonString: string,
): SafeParseResult<CreatePlaybackIdUserAgents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePlaybackIdUserAgents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePlaybackIdUserAgents' from JSON`,
  );
}

/** @internal */
export const CreatePlaybackIdAccessRestrictions$inboundSchema: z.ZodMiniType<
  CreatePlaybackIdAccessRestrictions,
  unknown
> = z.object({
  domains: types.optional(z.lazy(() => CreatePlaybackIdDomains$inboundSchema)),
  userAgents: types.optional(
    z.lazy(() => CreatePlaybackIdUserAgents$inboundSchema),
  ),
});

export function createPlaybackIdAccessRestrictionsFromJSON(
  jsonString: string,
): SafeParseResult<CreatePlaybackIdAccessRestrictions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePlaybackIdAccessRestrictions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePlaybackIdAccessRestrictions' from JSON`,
  );
}

/** @internal */
export const Resolution$inboundSchema: z.ZodMiniType<Resolution, unknown> =
  openEnums.inboundSchema(Resolution);

/** @internal */
export const CreatePlaybackId$inboundSchema: z.ZodMiniType<
  CreatePlaybackId,
  unknown
> = z.object({
  id: types.optional(types.string()),
  accessPolicy: types.optional(AccessPolicy$inboundSchema),
  accessRestrictions: types.optional(
    z.lazy(() => CreatePlaybackIdAccessRestrictions$inboundSchema),
  ),
  resolution: types.optional(Resolution$inboundSchema),
});

export function createPlaybackIdFromJSON(
  jsonString: string,
): SafeParseResult<CreatePlaybackId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePlaybackId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePlaybackId' from JSON`,
  );
}
