/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Displays the result of the request.
 */
export type CreateSigningKeyResponseDTO = {
  /**
   * A unique identifier is generated by FastPix for the signing keys.
   */
  id?: string | undefined;
  /**
   * A private key is a byte encoded secret key used to create a signed JSON Web Token (JWT) for authentication.
   */
  privateKey?: string | undefined;
  /**
   * Time the Signing key was generated, defined as a localDateTime (UTC Time).
   */
  createdAt?: Date | undefined;
};

/** @internal */
export const CreateSigningKeyResponseDTO$inboundSchema: z.ZodMiniType<
  CreateSigningKeyResponseDTO,
  unknown
> = z.object({
  id: types.optional(types.string()),
  privateKey: types.optional(types.string()),
  createdAt: types.optional(types.date()),
});

export function createSigningKeyResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<CreateSigningKeyResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSigningKeyResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSigningKeyResponseDTO' from JSON`,
  );
}
