/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Pagination organizes content into pages for better readability and navigation.
 */
export type DataPagination = {
  /**
   * The total number of records retrieved within the timespan.
   *
   * @remarks
   */
  totalRecords?: number | undefined;
  /**
   * The current offset value.
   *
   * @remarks
   *
   * Default: 1
   */
  currentOffset?: number | undefined;
  /**
   * The total number of offsets based on limit.
   *
   * @remarks
   */
  offsetCount?: number | undefined;
};

/** @internal */
export const DataPagination$inboundSchema: z.ZodMiniType<
  DataPagination,
  unknown
> = z.object({
  totalRecords: types.optional(types.number()),
  currentOffset: types.optional(types.number()),
  offsetCount: types.optional(types.number()),
});

export function dataPaginationFromJSON(
  jsonString: string,
): SafeParseResult<DataPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataPagination' from JSON`,
  );
}
