/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DeleteSigningKeyResponseData = {
  /**
   * Human-readable confirmation message returned by the API on successful deletion.
   */
  message?: string | undefined;
};

export type DeleteSigningKeyResponse = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * Optional informational payload returned by the API on successful deletion.
   */
  data?: DeleteSigningKeyResponseData | undefined;
};

/** @internal */
export const DeleteSigningKeyResponse$inboundSchema: z.ZodMiniType<
  DeleteSigningKeyResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(
    z.object({ message: types.optional(types.string()) }),
  ),
});

export function deleteSigningKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSigningKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSigningKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSigningKeyResponse' from JSON`,
  );
}
