/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DirectUploadResponse,
  DirectUploadResponse$inboundSchema,
} from "./directuploadresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Determines the media's status, which can be one of the possible values.
 */
export const DirectUploadStatus = {
  Waiting: "waiting",
} as const;
/**
 * Determines the media's status, which can be one of the possible values.
 */
export type DirectUploadStatus = ClosedEnum<typeof DirectUploadStatus>;

/**
 * Displays the result of the request.
 */
export type DirectUpload = {
  /**
   * The unique identifier assigned to the media when created. The value must be a valid UUID.
   */
  uploadId?: string | undefined;
  /**
   * Indicates if the upload was a trial.
   */
  trial?: boolean | undefined;
  /**
   * Determines the media's status, which can be one of the possible values.
   */
  status?: DirectUploadStatus | undefined;
  /**
   * The url hosts the media file for FastPix, which needs to be download to use further.  It supports formats like MP3, MP4, MOV, MKV, or TS, and includes text tracks for subtitles/CC (SRT file/VTT file). While FastPix can handle various audio and video formats and codecs, using standard inputs can help with optimal processing speed.
   */
  url?: string | undefined;
  /**
   * The duration set for the validity of the upload URL. If the upload isn't completed within this timespan, it's marked as timed out.
   *
   * @remarks
   */
  timeout?: number | undefined;
  /**
   * Upload media directly from a device using the url name or enter "*" to allow all.
   */
  corsOrigin?: string | undefined;
  pushMediaSettings?: DirectUploadResponse | undefined;
};

/** @internal */
export const DirectUploadStatus$inboundSchema: z.ZodMiniEnum<
  typeof DirectUploadStatus
> = z.enum(DirectUploadStatus);

/** @internal */
export const DirectUpload$inboundSchema: z.ZodMiniType<DirectUpload, unknown> =
  z.object({
    uploadId: types.optional(types.string()),
    trial: types.optional(types.boolean()),
    status: types.optional(DirectUploadStatus$inboundSchema),
    url: types.optional(types.string()),
    timeout: z._default(types.number(), 14400),
    corsOrigin: types.optional(types.string()),
    pushMediaSettings: types.optional(DirectUploadResponse$inboundSchema),
  });

export function directUploadFromJSON(
  jsonString: string,
): SafeParseResult<DirectUpload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DirectUpload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DirectUpload' from JSON`,
  );
}
