/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { PolicyAction, PolicyAction$outboundSchema } from "./policyaction.js";

/**
 * Restrictions based on the originating domain of a request
 */
export type DomainRestrictions = {
  /**
   * Policy action type
   */
  defaultPolicy?: PolicyAction | undefined;
  /**
   * A list of domain names or patterns that are explicitly allowed access
   */
  allow?: Array<string> | undefined;
  /**
   * A list of domain names or patterns that are explicitly denied access
   */
  deny?: Array<string> | undefined;
};

/** @internal */
export type DomainRestrictions$Outbound = {
  defaultPolicy?: string | undefined;
  allow?: Array<string> | undefined;
  deny?: Array<string> | undefined;
};

/** @internal */
export const DomainRestrictions$outboundSchema: z.ZodMiniType<
  DomainRestrictions$Outbound,
  DomainRestrictions
> = z.object({
  defaultPolicy: z.optional(PolicyAction$outboundSchema),
  allow: z.optional(z.array(z.string())),
  deny: z.optional(z.array(z.string())),
});

export function domainRestrictionsToJSON(
  domainRestrictions: DomainRestrictions,
): string {
  return JSON.stringify(
    DomainRestrictions$outboundSchema.parse(domainRestrictions),
  );
}
