/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DrmIdResponse = {
  /**
   * The unique identifier of the DRM configuration.
   */
  id?: string | undefined;
};

/** @internal */
export const DrmIdResponse$inboundSchema: z.ZodMiniType<
  DrmIdResponse,
  unknown
> = z.object({
  id: types.optional(types.string()),
});

export function drmIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DrmIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DrmIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DrmIdResponse' from JSON`,
  );
}
