/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * views affected by the specific errors.
 */
export type ErrorDetailsPercentage = number | number;

export type ErrorDetails = {
  /**
   * views affected by the specific errors.
   */
  percentage?: number | number | null | undefined;
  /**
   * Information about the specific error.
   */
  notes?: string | null | undefined;
  /**
   * error message or description.
   */
  message?: string | null | undefined;
  /**
   * The timestamp of when the error was last observed.
   */
  lastSeen?: string | null | undefined;
  /**
   * Unique identifier for the error instance.
   */
  id?: string | null | undefined;
  /**
   * A brief description of the error.
   */
  description?: string | null | undefined;
  /**
   * Number of occurrences of the specific error.
   */
  count?: number | null | undefined;
  /**
   * Error code associated with the specific error.
   */
  code?: string | null | undefined;
};

/** @internal */
export const ErrorDetailsPercentage$inboundSchema: z.ZodMiniType<
  ErrorDetailsPercentage,
  unknown
> = smartUnion([types.number(), types.number()]);

export function errorDetailsPercentageFromJSON(
  jsonString: string,
): SafeParseResult<ErrorDetailsPercentage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorDetailsPercentage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorDetailsPercentage' from JSON`,
  );
}

/** @internal */
export const ErrorDetails$inboundSchema: z.ZodMiniType<ErrorDetails, unknown> =
  z.object({
    percentage: z.optional(
      z.nullable(smartUnion([types.number(), types.number()])),
    ),
    notes: z.optional(z.nullable(types.string())),
    message: z.optional(z.nullable(types.string())),
    lastSeen: z.optional(z.nullable(types.string())),
    id: z.optional(z.nullable(types.string())),
    description: z.optional(z.nullable(types.string())),
    count: z.optional(z.nullable(types.number())),
    code: z.optional(z.nullable(types.string())),
  });

export function errorDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ErrorDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorDetails' from JSON`,
  );
}
