/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  GetAllSigningKeysResponseDto,
  GetAllSigningKeysResponseDto$inboundSchema,
} from "./getallsigningkeysresponsedto.js";
import {
  SigningKeysPagination,
  SigningKeysPagination$inboundSchema,
} from "./signingkeyspagination.js";

export type GetAllSigningKeysResponse = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  data?: Array<GetAllSigningKeysResponseDto> | undefined;
  /**
   * Pagination organizes content into pages for better readability and navigation.
   */
  pagination?: SigningKeysPagination | undefined;
};

/** @internal */
export const GetAllSigningKeysResponse$inboundSchema: z.ZodMiniType<
  GetAllSigningKeysResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(GetAllSigningKeysResponseDto$inboundSchema)),
  pagination: types.optional(SigningKeysPagination$inboundSchema),
});

export function getAllSigningKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllSigningKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllSigningKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllSigningKeysResponse' from JSON`,
  );
}
