/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Displays the result of the request.
 */
export type GetPublicPemUsingSigningKeyIdResponseDTOData = {
  /**
   * FastPix generates a unique identifier for each workspace.
   */
  workspaceId?: string | undefined;
  signingKeyId?: string | undefined;
  /**
   * A public key is a byte encoded key used to create a signed JSON Web Token (JWT) for authentication.
   */
  publicKey?: string | undefined;
};

/**
 * Displays the result of the request.
 */
export type GetPublicPemUsingSigningKeyIdResponseDTO = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * Displays the result of the request.
   */
  data?: GetPublicPemUsingSigningKeyIdResponseDTOData | undefined;
};

/** @internal */
export const GetPublicPemUsingSigningKeyIdResponseDTOData$inboundSchema:
  z.ZodMiniType<GetPublicPemUsingSigningKeyIdResponseDTOData, unknown> = z
    .object({
      workspaceId: types.optional(types.string()),
      signingKeyId: types.optional(types.string()),
      publicKey: types.optional(types.string()),
    });

export function getPublicPemUsingSigningKeyIdResponseDTODataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicPemUsingSigningKeyIdResponseDTOData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicPemUsingSigningKeyIdResponseDTOData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPublicPemUsingSigningKeyIdResponseDTOData' from JSON`,
  );
}

/** @internal */
export const GetPublicPemUsingSigningKeyIdResponseDTO$inboundSchema:
  z.ZodMiniType<GetPublicPemUsingSigningKeyIdResponseDTO, unknown> = z.object({
    success: types.optional(types.boolean()),
    data: types.optional(
      z.lazy(() => GetPublicPemUsingSigningKeyIdResponseDTOData$inboundSchema),
    ),
  });

export function getPublicPemUsingSigningKeyIdResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublicPemUsingSigningKeyIdResponseDTO,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublicPemUsingSigningKeyIdResponseDTO$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPublicPemUsingSigningKeyIdResponseDTO' from JSON`,
  );
}
