/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  GetCreateLiveStreamResponseDTO,
  GetCreateLiveStreamResponseDTO$inboundSchema,
} from "./getcreatelivestreamresponsedto.js";
import {
  LiveStreamPagination,
  LiveStreamPagination$inboundSchema,
} from "./livestreampagination.js";

/**
 * Displays the result of the request.
 */
export type GetStreamsResponse = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * Displays the result of the request.
   */
  data?: Array<GetCreateLiveStreamResponseDTO> | undefined;
  /**
   * Pagination organizes content into pages for better readability and navigation.
   */
  pagination?: LiveStreamPagination | undefined;
};

/** @internal */
export const GetStreamsResponse$inboundSchema: z.ZodMiniType<
  GetStreamsResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(GetCreateLiveStreamResponseDTO$inboundSchema)),
  pagination: types.optional(LiveStreamPagination$inboundSchema),
});

export function getStreamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStreamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStreamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStreamsResponse' from JSON`,
  );
}
