/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type LiveSimulcast = {
  /**
   * When you create the new simulcast, FastPix assign a universal unique identifier which can contain a maximum of 255 characters.
   */
  simulcastId?: string | undefined;
  /**
   * The RTMPS hostname, combined with the application name, is crucial for connecting to third-party live streaming services and transmitting the live stream.
   */
  url?: string | undefined;
  /**
   * A unique stream key is generated for streaming, allowing the user to start streaming on any third-party platform using this key.
   */
  streamKey?: string | undefined;
  /**
   * When the value is true, the simulcast must be enabled for the given stream
   */
  isEnabled?: boolean | undefined;
  /**
   * You can search for videos with specific key value pairs using metadata, when you tag a video in "key":"value"s pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
   */
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const LiveSimulcast$inboundSchema: z.ZodMiniType<
  LiveSimulcast,
  unknown
> = z.object({
  simulcastId: types.optional(types.string()),
  url: types.optional(types.string()),
  streamKey: types.optional(types.string()),
  isEnabled: types.optional(types.boolean()),
  metadata: types.optional(z.record(z.string(), types.string())),
});

export function liveSimulcastFromJSON(
  jsonString: string,
): SafeParseResult<LiveSimulcast, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LiveSimulcast$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LiveSimulcast' from JSON`,
  );
}
