/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";

/**
 * The list of mediaId(s) you want to perform the operation on.
 */
export type MediaIdsRequest = {
  mediaIds: Array<string>;
};

/** @internal */
export type MediaIdsRequest$Outbound = {
  mediaIds: Array<string>;
};

/** @internal */
export const MediaIdsRequest$outboundSchema: z.ZodMiniType<
  MediaIdsRequest$Outbound,
  MediaIdsRequest
> = z.object({
  mediaIds: z.array(z.string()),
});

export function mediaIdsRequestToJSON(
  mediaIdsRequest: MediaIdsRequest,
): string {
  return JSON.stringify(MediaIdsRequest$outboundSchema.parse(mediaIdsRequest));
}
