/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response returned when an upload is cancelled.
 */
export type MediaCancelResponse = {
  /**
   * The unique identifier of the cancelled upload.
   */
  uploadId?: string | undefined;
  /**
   * Indicates if the upload was a trial.
   */
  trial?: boolean | undefined;
  /**
   * The status of the upload after cancellation.
   */
  status?: string | undefined;
  /**
   * The upload URL (if available) after cancellation.
   */
  url?: string | undefined;
  /**
   * The timeout value for the upload.
   */
  timeout?: number | undefined;
  /**
   * CORS origin allowed for the upload.
   */
  corsOrigin?: string | undefined;
  /**
   * The maximum resolution allowed for the upload.
   */
  maxResolution?: string | undefined;
  /**
   * The access policy for the upload.
   */
  accessPolicy?: string | undefined;
  /**
   * You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
   *
   * @remarks
   */
  metadata?: { [k: string]: string } | undefined;
  /**
   * Title of the media file.
   */
  title?: string | undefined;
  /**
   * The unique identifier of the user who created this media.
   */
  creatorId?: string | undefined;
};

/** @internal */
export const MediaCancelResponse$inboundSchema: z.ZodMiniType<
  MediaCancelResponse,
  unknown
> = z.object({
  uploadId: types.optional(types.string()),
  trial: types.optional(types.boolean()),
  status: types.optional(types.string()),
  url: types.optional(types.string()),
  timeout: types.optional(types.number()),
  corsOrigin: types.optional(types.string()),
  maxResolution: types.optional(types.string()),
  accessPolicy: types.optional(types.string()),
  metadata: types.optional(z.record(z.string(), types.string())),
  title: types.optional(types.string()),
  creatorId: types.optional(types.string()),
});

export function mediaCancelResponseFromJSON(
  jsonString: string,
): SafeParseResult<MediaCancelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MediaCancelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaCancelResponse' from JSON`,
  );
}
