/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Retrieves overall values for a specified metric
 */
export type MetricsOverallDataDetails = {
  /**
   * metric value calculated based on the applied filters.
   */
  value?: number | null | undefined;
  /**
   * Total time watched across all views, represented in milliseconds.
   */
  totalWatchTime?: number | null | undefined;
  /**
   * The count of unique viewers who interacted with the content.
   */
  uniqueViews?: number | null | undefined;
  /**
   * The total number of views recorded.
   */
  totalViews?: number | null | undefined;
  /**
   * Total time spent playing the video, represented in milliseconds.
   */
  totalPlayTime?: number | null | undefined;
  /**
   * A global metric value that reflects the overall performance of the specified metric across the entire dataset for the given timespan.
   */
  globalValue?: number | null | undefined;
};

/** @internal */
export const MetricsOverallDataDetails$inboundSchema: z.ZodMiniType<
  MetricsOverallDataDetails,
  unknown
> = z.object({
  value: z.optional(z.nullable(types.number())),
  totalWatchTime: z.optional(z.nullable(types.number())),
  uniqueViews: z.optional(z.nullable(types.number())),
  totalViews: z.optional(z.nullable(types.number())),
  totalPlayTime: z.optional(z.nullable(types.number())),
  globalValue: z.optional(z.nullable(types.number())),
});

export function metricsOverallDataDetailsFromJSON(
  jsonString: string,
): SafeParseResult<MetricsOverallDataDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricsOverallDataDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricsOverallDataDetails' from JSON`,
  );
}
