/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Retrieves breakdown values for a specified metric and timespan
 */
export type MetricsTimeseriesmetadataDetails = {
  /**
   * the unit for aggregating the timeseries data.
   */
  granularity?: string | undefined;
  /**
   * defines the field or dimension on which the aggregation is to be   applied.
   */
  aggregation?: string | undefined;
};

/** @internal */
export const MetricsTimeseriesmetadataDetails$inboundSchema: z.ZodMiniType<
  MetricsTimeseriesmetadataDetails,
  unknown
> = z.object({
  granularity: types.optional(types.string()),
  aggregation: types.optional(types.string()),
});

export function metricsTimeseriesmetadataDetailsFromJSON(
  jsonString: string,
): SafeParseResult<MetricsTimeseriesmetadataDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricsTimeseriesmetadataDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricsTimeseriesmetadataDetails' from JSON`,
  );
}
