/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * metadata that has to be paased for metric calculations.
 */
export type MetricsOverallmetadataDetails = {
  /**
   * defines the field or dimension on which the aggregation is to be   applied.
   */
  aggregation?: string | undefined;
};

/** @internal */
export const MetricsOverallmetadataDetails$inboundSchema: z.ZodMiniType<
  MetricsOverallmetadataDetails,
  unknown
> = z.object({
  aggregation: types.optional(types.string()),
});

export function metricsOverallmetadataDetailsFromJSON(
  jsonString: string,
): SafeParseResult<MetricsOverallmetadataDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricsOverallmetadataDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricsOverallmetadataDetails' from JSON`,
  );
}
