/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Pagination organizes content into pages for better readability and navigation.
 */
export type Pagination = {
  /**
   * It gives the total number of media assets that are accessible overall.
   */
  totalRecords?: number | undefined;
  /**
   * Offset determines the current point for data retrieval within a paginated list.
   */
  currentOffset?: number | undefined;
  /**
   * The offset count is expressed as total records by limit
   */
  offsetCount?: number | undefined;
};

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z
  .object({
    totalRecords: types.optional(types.number()),
    currentOffset: types.optional(types.number()),
    offsetCount: types.optional(types.number()),
  });

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}
