/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PatchResponseData,
  PatchResponseData$inboundSchema,
} from "./patchresponsedata.js";

/**
 * Displays the result of the request.
 */
export type PatchResponseDTO = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * Displays the result of the request.
   */
  data?: PatchResponseData | undefined;
};

/** @internal */
export const PatchResponseDTO$inboundSchema: z.ZodMiniType<
  PatchResponseDTO,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(PatchResponseData$inboundSchema),
});

export function patchResponseDTOFromJSON(
  jsonString: string,
): SafeParseResult<PatchResponseDTO, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchResponseDTO$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchResponseDTO' from JSON`,
  );
}
