/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";

export type PatchLiveStreamRequest = {
  /**
   * You can search for videos with specific key value pairs using metadata, when you tag a video in "key":"value"s pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
   */
  metadata?: { [k: string]: string } | undefined;
  /**
   * In case the software streaming the live, gets disrupted for any reason and gets disconnected from FastPix, the reconnect window defines the duration FastPix waits before automatically terminating the stream. Before starting the stream, you can set the reconnect window time which is up to 1800 seconds.
   */
  reconnectWindow?: number | undefined;
};

/** @internal */
export type PatchLiveStreamRequest$Outbound = {
  metadata?: { [k: string]: string } | undefined;
  reconnectWindow: number;
};

/** @internal */
export const PatchLiveStreamRequest$outboundSchema: z.ZodMiniType<
  PatchLiveStreamRequest$Outbound,
  PatchLiveStreamRequest
> = z.object({
  metadata: z.optional(z.record(z.string(), z.string())),
  reconnectWindow: z._default(z.int(), 60),
});

export function patchLiveStreamRequestToJSON(
  patchLiveStreamRequest: PatchLiveStreamRequest,
): string {
  return JSON.stringify(
    PatchLiveStreamRequest$outboundSchema.parse(patchLiveStreamRequest),
  );
}
