/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AccessPolicy, AccessPolicy$inboundSchema } from "./accesspolicy.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PolicyAction, PolicyAction$inboundSchema } from "./policyaction.js";

/**
 * Restrictions based on the originating domain of a request (for example, whether requests from certain websites must be allowed or blocked).
 */
export type PlaybackIdDomains = {
  /**
   * Policy action type
   */
  defaultPolicy?: PolicyAction | undefined;
  /**
   * A list of domains that are explicitly allowed access.
   */
  allow?: Array<string> | undefined;
  /**
   * A list of domains that are explicitly blocked from accessing the resource.
   */
  deny?: Array<string> | undefined;
};

/**
 * Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
 */
export type PlaybackIdUserAgents = {
  /**
   * Policy action type
   */
  defaultPolicy?: PolicyAction | undefined;
  /**
   * A list of specific user agents that are allowed to access the resource.
   */
  allow?: Array<string> | undefined;
  /**
   * A list of specific user agents that are blocked.
   */
  deny?: Array<string> | undefined;
};

/**
 * Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
 */
export type PlaybackIdAccessRestrictions = {
  /**
   * Restrictions based on the originating domain of a request (for example, whether requests from certain websites must be allowed or blocked).
   */
  domains?: PlaybackIdDomains | undefined;
  /**
   * Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
   */
  userAgents?: PlaybackIdUserAgents | undefined;
};

/**
 * A collection of Playback ID objects utilized for crafting HLS playback urls.
 */
export type PlaybackId = {
  /**
   * A unique identifier is generated by FastPix for the playbacks.
   */
  id?: string | undefined;
  /**
   * Access policy for media content
   */
  accessPolicy?: AccessPolicy | undefined;
  /**
   * Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
   */
  accessRestrictions?: PlaybackIdAccessRestrictions | undefined;
};

/** @internal */
export const PlaybackIdDomains$inboundSchema: z.ZodMiniType<
  PlaybackIdDomains,
  unknown
> = z.object({
  defaultPolicy: types.optional(PolicyAction$inboundSchema),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function playbackIdDomainsFromJSON(
  jsonString: string,
): SafeParseResult<PlaybackIdDomains, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaybackIdDomains$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaybackIdDomains' from JSON`,
  );
}

/** @internal */
export const PlaybackIdUserAgents$inboundSchema: z.ZodMiniType<
  PlaybackIdUserAgents,
  unknown
> = z.object({
  defaultPolicy: types.optional(PolicyAction$inboundSchema),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function playbackIdUserAgentsFromJSON(
  jsonString: string,
): SafeParseResult<PlaybackIdUserAgents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaybackIdUserAgents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaybackIdUserAgents' from JSON`,
  );
}

/** @internal */
export const PlaybackIdAccessRestrictions$inboundSchema: z.ZodMiniType<
  PlaybackIdAccessRestrictions,
  unknown
> = z.object({
  domains: types.optional(z.lazy(() => PlaybackIdDomains$inboundSchema)),
  userAgents: types.optional(z.lazy(() => PlaybackIdUserAgents$inboundSchema)),
});

export function playbackIdAccessRestrictionsFromJSON(
  jsonString: string,
): SafeParseResult<PlaybackIdAccessRestrictions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaybackIdAccessRestrictions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaybackIdAccessRestrictions' from JSON`,
  );
}

/** @internal */
export const PlaybackId$inboundSchema: z.ZodMiniType<PlaybackId, unknown> = z
  .object({
    id: types.optional(types.string()),
    accessPolicy: types.optional(AccessPolicy$inboundSchema),
    accessRestrictions: types.optional(
      z.lazy(() => PlaybackIdAccessRestrictions$inboundSchema),
    ),
  });

export function playbackIdFromJSON(
  jsonString: string,
): SafeParseResult<PlaybackId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaybackId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaybackId' from JSON`,
  );
}
