/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PlaybackIdSuccessResponseData = {
  /**
   * Unique identifier for the playbackId
   */
  id?: string | undefined;
  /**
   * Determines if access to the streamed content is kept private or available to all.
   */
  accessPolicy?: string | undefined;
};

/**
 * Displays the result of the request.
 */
export type PlaybackIdSuccessResponse = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  data?: PlaybackIdSuccessResponseData | undefined;
};

/** @internal */
export const PlaybackIdSuccessResponseData$inboundSchema: z.ZodMiniType<
  PlaybackIdSuccessResponseData,
  unknown
> = z.object({
  id: types.optional(types.string()),
  accessPolicy: types.optional(types.string()),
});

export function playbackIdSuccessResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PlaybackIdSuccessResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaybackIdSuccessResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaybackIdSuccessResponseData' from JSON`,
  );
}

/** @internal */
export const PlaybackIdSuccessResponse$inboundSchema: z.ZodMiniType<
  PlaybackIdSuccessResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(
    z.lazy(() => PlaybackIdSuccessResponseData$inboundSchema),
  ),
});

export function playbackIdSuccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlaybackIdSuccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaybackIdSuccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaybackIdSuccessResponse' from JSON`,
  );
}
