/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PlaylistByIdResponseMediaListItem,
  PlaylistByIdResponseMediaListItem$inboundSchema,
} from "./playlistbyidresponsemedialistitem.js";

export type PlaylistByIdResponseDataManual = {
  /**
   * The unique id of the playlist
   */
  id?: string | undefined;
  /**
   * The name of the playlist set by the user
   */
  name?: string | undefined;
  /**
   * Unique string value assigned by user to the playlist.
   */
  referenceId?: string | undefined;
  /**
   * type of the playlist, when it was created
   */
  type: "manual";
  /**
   * Description of the playlist set by the user.
   */
  description?: string | undefined;
  mediaList?: Array<PlaylistByIdResponseMediaListItem> | undefined;
  /**
   * The unique id of the workspace in which the playlist is present.
   */
  workspaceId?: string | undefined;
  /**
   * Timestamp of playlist creation.
   */
  createdAt?: Date | undefined;
  /**
   * Playlist's most recent update timestamp.
   */
  updatedAt?: Date | undefined;
  /**
   * No. of media present in the playlist
   */
  mediaCount?: number | undefined;
};

/** @internal */
export const PlaylistByIdResponseDataManual$inboundSchema: z.ZodMiniType<
  PlaylistByIdResponseDataManual,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  referenceId: types.optional(types.string()),
  type: types.literal("manual"),
  description: types.optional(types.string()),
  mediaList: types.optional(
    z.array(PlaylistByIdResponseMediaListItem$inboundSchema),
  ),
  workspaceId: types.optional(types.string()),
  createdAt: types.optional(types.date()),
  updatedAt: types.optional(types.date()),
  mediaCount: types.optional(types.number()),
});

export function playlistByIdResponseDataManualFromJSON(
  jsonString: string,
): SafeParseResult<PlaylistByIdResponseDataManual, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaylistByIdResponseDataManual$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaylistByIdResponseDataManual' from JSON`,
  );
}
