/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PlaylistByIdResponseMediaListItem,
  PlaylistByIdResponseMediaListItem$inboundSchema,
} from "./playlistbyidresponsemedialistitem.js";
import {
  PlaylistByIdResponseMetadata,
  PlaylistByIdResponseMetadata$inboundSchema,
} from "./playlistbyidresponsemetadata.js";
import { PlaylistOrder, PlaylistOrder$inboundSchema } from "./playlistorder.js";

export type PlaylistByIdResponseDataSmart = {
  /**
   * The unique id of the playlist
   */
  id?: string | undefined;
  /**
   * The name of the playlist set by the user
   */
  name?: string | undefined;
  /**
   * Unique string value assigned by user to the playlist.
   */
  referenceId?: string | undefined;
  /**
   * type of the playlist, when it was created
   */
  type: "smart";
  /**
   * Description of the playlist set by the user.
   */
  description?: string | undefined;
  /**
   * Determines the insertion order of media into playlist.
   */
  playOrder: PlaylistOrder;
  /**
   * Required when the playlist type is `smart`. Media created between `startDate` and `endDate` of `createdDate` is added. Optionally, you can include media based on `updatedDate`.
   */
  metadata: PlaylistByIdResponseMetadata;
  mediaList?: Array<PlaylistByIdResponseMediaListItem> | undefined;
  /**
   * The unique id of the workspace in which the playlist is present.
   */
  workspaceId?: string | undefined;
  /**
   * Timestamp of playlist creation.
   */
  createdAt?: Date | undefined;
  /**
   * Playlist's most recent update timestamp.
   */
  updatedAt?: Date | undefined;
  /**
   * No. of media present in the playlist
   */
  mediaCount?: number | undefined;
};

/** @internal */
export const PlaylistByIdResponseDataSmart$inboundSchema: z.ZodMiniType<
  PlaylistByIdResponseDataSmart,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  referenceId: types.optional(types.string()),
  type: types.literal("smart"),
  description: types.optional(types.string()),
  playOrder: PlaylistOrder$inboundSchema,
  metadata: PlaylistByIdResponseMetadata$inboundSchema,
  mediaList: types.optional(
    z.array(PlaylistByIdResponseMediaListItem$inboundSchema),
  ),
  workspaceId: types.optional(types.string()),
  createdAt: types.optional(types.date()),
  updatedAt: types.optional(types.date()),
  mediaCount: types.optional(types.number()),
});

export function playlistByIdResponseDataSmartFromJSON(
  jsonString: string,
): SafeParseResult<PlaylistByIdResponseDataSmart, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaylistByIdResponseDataSmart$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaylistByIdResponseDataSmart' from JSON`,
  );
}
