/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PlaylistDeleteResponse = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
};

/** @internal */
export const PlaylistDeleteResponse$inboundSchema: z.ZodMiniType<
  PlaylistDeleteResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
});

export function playlistDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlaylistDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaylistDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaylistDeleteResponse' from JSON`,
  );
}
