/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import {
  BasicAccessPolicy,
  BasicAccessPolicy$outboundSchema,
} from "./basicaccesspolicy.js";

export type PlaybackIdRequest = {
  /**
   * Basic access policy for media content
   */
  accessPolicy?: BasicAccessPolicy | undefined;
};

/** @internal */
export type PlaybackIdRequest$Outbound = {
  accessPolicy: string;
};

/** @internal */
export const PlaybackIdRequest$outboundSchema: z.ZodMiniType<
  PlaybackIdRequest$Outbound,
  PlaybackIdRequest
> = z.object({
  accessPolicy: z._default(BasicAccessPolicy$outboundSchema, "public"),
});

export function playbackIdRequestToJSON(
  playbackIdRequest: PlaybackIdRequest,
): string {
  return JSON.stringify(
    PlaybackIdRequest$outboundSchema.parse(playbackIdRequest),
  );
}
