/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import {
  AccessRestrictions,
  AccessRestrictions$Outbound,
  AccessRestrictions$outboundSchema,
} from "./accessrestrictions.js";
import {
  BasicAccessPolicy,
  BasicAccessPolicy$outboundSchema,
} from "./basicaccesspolicy.js";

/**
 * Displays the result of the playback settings.
 */
export type PlaybackSettings = {
  /**
   * Basic access policy for media content
   */
  accessPolicy?: BasicAccessPolicy | undefined;
  /**
   * Access control restrictions applied to the playback ID.
   */
  accessRestrictions?: AccessRestrictions | undefined;
};

/** @internal */
export type PlaybackSettings$Outbound = {
  accessPolicy: string;
  accessRestrictions?: AccessRestrictions$Outbound | undefined;
};

/** @internal */
export const PlaybackSettings$outboundSchema: z.ZodMiniType<
  PlaybackSettings$Outbound,
  PlaybackSettings
> = z.object({
  accessPolicy: z._default(BasicAccessPolicy$outboundSchema, "public"),
  accessRestrictions: z.optional(
    z.lazy(() => AccessRestrictions$outboundSchema),
  ),
});

export function playbackSettingsToJSON(
  playbackSettings: PlaybackSettings,
): string {
  return JSON.stringify(
    PlaybackSettings$outboundSchema.parse(playbackSettings),
  );
}
