/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A collection of Playback ID objects utilized for crafting HLS playback urls.
 */
export type PlaybackIdResponse = {
  /**
   * Unique identifier for the playbackId
   */
  id?: string | undefined;
  /**
   * Determines if access to the streamed content is kept private or available to all.
   */
  accessPolicy?: string | undefined;
};

/** @internal */
export const PlaybackIdResponse$inboundSchema: z.ZodMiniType<
  PlaybackIdResponse,
  unknown
> = z.object({
  id: types.optional(types.string()),
  accessPolicy: types.optional(types.string()),
});

export function playbackIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlaybackIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaybackIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaybackIdResponse' from JSON`,
  );
}
