/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { DateRange, DateRange$inboundSchema } from "./daterange.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Required when the playlist type is `smart`. Media created between `startDate` and `endDate` of `createdDate` is added. Optionally, you can include media based on `updatedDate`.
 */
export type PlaylistByIdResponseMetadata = {
  /**
   * Date range with start and end dates.
   */
  createdDate?: DateRange | undefined;
  /**
   * Date range with start and end dates.
   */
  updatedDate?: DateRange | undefined;
};

/** @internal */
export const PlaylistByIdResponseMetadata$inboundSchema: z.ZodMiniType<
  PlaylistByIdResponseMetadata,
  unknown
> = z.object({
  createdDate: types.optional(DateRange$inboundSchema),
  updatedDate: types.optional(DateRange$inboundSchema),
});

export function playlistByIdResponseMetadataFromJSON(
  jsonString: string,
): SafeParseResult<PlaylistByIdResponseMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaylistByIdResponseMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaylistByIdResponseMetadata' from JSON`,
  );
}
