/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PlaylistByIdResponseDataManual,
  PlaylistByIdResponseDataManual$inboundSchema,
} from "./playlistbyidresponsedatamanual.js";
import {
  PlaylistByIdResponseDataSmart,
  PlaylistByIdResponseDataSmart$inboundSchema,
} from "./playlistbyidresponsedatasmart.js";

export type PlaylistCreatedSchema =
  | PlaylistByIdResponseDataManual
  | PlaylistByIdResponseDataSmart
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const PlaylistCreatedSchema$inboundSchema: z.ZodMiniType<
  PlaylistCreatedSchema,
  unknown
> = discriminatedUnion("type", {
  manual: PlaylistByIdResponseDataManual$inboundSchema,
  smart: PlaylistByIdResponseDataSmart$inboundSchema,
});

export function playlistCreatedSchemaFromJSON(
  jsonString: string,
): SafeParseResult<PlaylistCreatedSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaylistCreatedSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaylistCreatedSchema' from JSON`,
  );
}
