/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { smartUnion } from "../types/smartUnion.js";

export type PullVideoInputSegment2 = {
  /**
   * The URL of the **video segment** to be added.
   *
   * @remarks
   * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve and process the segment successfully.
   * Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and performance.
   */
  url: string;
  /**
   * Flag indicating the segment should be inserted at the end.
   */
  insertAtEnd: boolean;
};

export type PullVideoInputSegment1 = {
  /**
   * The URL of the **video segment** to be added.
   *
   * @remarks
   * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve and process the segment successfully.
   * Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and performance.
   */
  url: string;
  /**
   * The timestamp(in seconds) at which the segment must be inserted.
   */
  insertAt: number;
};

export type PullVideoInputSegmentUnion =
  | PullVideoInputSegment1
  | PullVideoInputSegment2;

export type PullVideoInput = {
  /**
   * Defines the type of input.
   *
   * @remarks
   */
  type?: string | undefined;
  /**
   * The URL hosts the media file for FastPix, which needs to be downloaded to use further. It supports formats like MP3, MP4, MOV, MKV, or TS, and includes text tracks for subtitles or closed captions (SRT/VTT files). The URL must be valid, publicly accessible, and downloadable to ensure FastPix can fetch the file successfully.
   *
   * @remarks
   *
   * While FastPix can handle various audio and video formats and codecs, using standard and widely supported formats helps achieve optimal processing speed.
   */
  url?: string | undefined;
  /**
   * Start time indicates where encoding must begin within the video file. For example, if you want to encode a segment from 3 minutes (180 seconds) to 6 minutes (360 seconds) in a 10-minute (600 seconds) video, the start time is 3 minutes (180 seconds). Note: Start time is always mentioned in seconds.
   *
   * @remarks
   */
  startTime?: number | undefined;
  /**
   * End time indicates where encoding must end within the video file. For example, if you want to encode a segment from 3 minutes (180 seconds) to 6 minutes (360 seconds) in a 10-minute (600 seconds) video, the end time is 6 minutes (360 seconds). Note: End time is always mentioned in seconds.
   *
   * @remarks
   */
  endTime?: number | undefined;
  /**
   * The URL of the **intro video** to be added at the beginning of the media file.
   *
   * @remarks
   * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can fetch the file successfully.
   * Supported video formats include **MP4, MOV, MKV, and TS** for optimal processing performance.
   */
  introUrl?: string | undefined;
  /**
   * The URL of the **outro video** to be added at the end of the media file.
   *
   * @remarks
   * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve the file successfully.
   * Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and processing speed.
   */
  outroUrl?: string | undefined;
  /**
   * The list of start and end times (in seconds) of the segments to be removed from the actual video.
   *
   * @remarks
   */
  expungeSegments?: Array<string> | undefined;
  /**
   * A list of media segments to be added or processed. Each segment includes details such as the URL of the media file and instructions on where it should be inserted in the final media composition. A segment can either specify an exact timestamp  (`insertAt`) or indicate that it must be added at the end (`insertAtEnd`).
   */
  segments?: Array<PullVideoInputSegment1 | PullVideoInputSegment2> | undefined;
};

/** @internal */
export type PullVideoInputSegment2$Outbound = {
  url: string;
  insertAtEnd: boolean;
};

/** @internal */
export const PullVideoInputSegment2$outboundSchema: z.ZodMiniType<
  PullVideoInputSegment2$Outbound,
  PullVideoInputSegment2
> = z.object({
  url: z.string(),
  insertAtEnd: z.boolean(),
});

export function pullVideoInputSegment2ToJSON(
  pullVideoInputSegment2: PullVideoInputSegment2,
): string {
  return JSON.stringify(
    PullVideoInputSegment2$outboundSchema.parse(pullVideoInputSegment2),
  );
}

/** @internal */
export type PullVideoInputSegment1$Outbound = {
  url: string;
  insertAt: number;
};

/** @internal */
export const PullVideoInputSegment1$outboundSchema: z.ZodMiniType<
  PullVideoInputSegment1$Outbound,
  PullVideoInputSegment1
> = z.object({
  url: z.string(),
  insertAt: z.int(),
});

export function pullVideoInputSegment1ToJSON(
  pullVideoInputSegment1: PullVideoInputSegment1,
): string {
  return JSON.stringify(
    PullVideoInputSegment1$outboundSchema.parse(pullVideoInputSegment1),
  );
}

/** @internal */
export type PullVideoInputSegmentUnion$Outbound =
  | PullVideoInputSegment1$Outbound
  | PullVideoInputSegment2$Outbound;

/** @internal */
export const PullVideoInputSegmentUnion$outboundSchema: z.ZodMiniType<
  PullVideoInputSegmentUnion$Outbound,
  PullVideoInputSegmentUnion
> = smartUnion([
  z.lazy(() => PullVideoInputSegment1$outboundSchema),
  z.lazy(() => PullVideoInputSegment2$outboundSchema),
]);

export function pullVideoInputSegmentUnionToJSON(
  pullVideoInputSegmentUnion: PullVideoInputSegmentUnion,
): string {
  return JSON.stringify(
    PullVideoInputSegmentUnion$outboundSchema.parse(pullVideoInputSegmentUnion),
  );
}

/** @internal */
export type PullVideoInput$Outbound = {
  type: string;
  url: string;
  startTime?: number | undefined;
  endTime?: number | undefined;
  introUrl?: string | undefined;
  outroUrl?: string | undefined;
  expungeSegments?: Array<string> | undefined;
  segments?:
    | Array<PullVideoInputSegment1$Outbound | PullVideoInputSegment2$Outbound>
    | undefined;
};

/** @internal */
export const PullVideoInput$outboundSchema: z.ZodMiniType<
  PullVideoInput$Outbound,
  PullVideoInput
> = z.object({
  type: z._default(z.string(), "video"),
  url: z._default(z.string(), "https://static.fastpix.io/fp-sample-video.mp4"),
  startTime: z.optional(z.int()),
  endTime: z.optional(z.int()),
  introUrl: z.optional(z.string()),
  outroUrl: z.optional(z.string()),
  expungeSegments: z.optional(z.array(z.string())),
  segments: z.optional(
    z.array(smartUnion([
      z.lazy(() => PullVideoInputSegment1$outboundSchema),
      z.lazy(() =>
        PullVideoInputSegment2$outboundSchema
      ),
    ])),
  ),
});

export function pullVideoInputToJSON(pullVideoInput: PullVideoInput): string {
  return JSON.stringify(PullVideoInput$outboundSchema.parse(pullVideoInput));
}
