/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";

export type SimulcastUpdateRequest = {
  /**
   * When set to false, the simulcast is disabled for the specified stream.
   */
  isEnabled?: boolean | undefined;
  /**
   * You can search for videos with specific key-value pairs using metadata, when you tag a video in "key":"value" pairs.
   */
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export type SimulcastUpdateRequest$Outbound = {
  isEnabled: boolean;
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const SimulcastUpdateRequest$outboundSchema: z.ZodMiniType<
  SimulcastUpdateRequest$Outbound,
  SimulcastUpdateRequest
> = z.object({
  isEnabled: z._default(z.boolean(), true),
  metadata: z.optional(z.record(z.string(), z.string())),
});

export function simulcastUpdateRequestToJSON(
  simulcastUpdateRequest: SimulcastUpdateRequest,
): string {
  return JSON.stringify(
    SimulcastUpdateRequest$outboundSchema.parse(simulcastUpdateRequest),
  );
}
