/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SimulcastdeleteResponse = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
};

/** @internal */
export const SimulcastdeleteResponse$inboundSchema: z.ZodMiniType<
  SimulcastdeleteResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
});

export function simulcastdeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<SimulcastdeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimulcastdeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimulcastdeleteResponse' from JSON`,
  );
}
