/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Displays the result of the request.
 */
export type SimulcastUpdateResponseData = {
  /**
   * When you create the new simulcast, FastPix assign a universal unique identifier which can contain a maximum of 255 characters.
   */
  simulcastId?: string | undefined;
  /**
   * The RTMP hostname, combined with the application name, is crucial for connecting to third-party live streaming services and transmitting the live stream.
   */
  url?: string | undefined;
  /**
   * A unique stream key is generated for streaming, allowing the user to start streaming on any third-party platform using this key.
   */
  streamKey?: string | undefined;
  /**
   * When set to false, the simulcast is disabled for the specified stream.
   */
  isEnabled?: boolean | undefined;
  /**
   * You can search for videos with specific key value pairs using metadata, when you tag a video in "key":"value"s pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
   */
  metadata?: { [k: string]: string } | undefined;
};

/**
 * Displays the result of the request.
 */
export type SimulcastUpdateResponse = {
  /**
   * Shows the request status. Returns true for success and false for failure.
   */
  success?: boolean | undefined;
  /**
   * Displays the result of the request.
   */
  data?: SimulcastUpdateResponseData | undefined;
};

/** @internal */
export const SimulcastUpdateResponseData$inboundSchema: z.ZodMiniType<
  SimulcastUpdateResponseData,
  unknown
> = z.object({
  simulcastId: types.optional(types.string()),
  url: types.optional(types.string()),
  streamKey: types.optional(types.string()),
  isEnabled: types.optional(types.boolean()),
  metadata: types.optional(z.record(z.string(), types.string())),
});

export function simulcastUpdateResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<SimulcastUpdateResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimulcastUpdateResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimulcastUpdateResponseData' from JSON`,
  );
}

/** @internal */
export const SimulcastUpdateResponse$inboundSchema: z.ZodMiniType<
  SimulcastUpdateResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.lazy(() => SimulcastUpdateResponseData$inboundSchema)),
});

export function simulcastUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<SimulcastUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimulcastUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimulcastUpdateResponse' from JSON`,
  );
}
