/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * The values in the list can be arranged in two ways: DESC (Descending) or ASC (Ascending).
 */
export const SortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The values in the list can be arranged in two ways: DESC (Descending) or ASC (Ascending).
 */
export type SortOrder = ClosedEnum<typeof SortOrder>;

/** @internal */
export const SortOrder$outboundSchema: z.ZodMiniEnum<typeof SortOrder> = z.enum(
  SortOrder,
);
