/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * This object contains the livestream playback response details for SRT Protocol
 */
export type SrtPlaybackResponse = {
  /**
   * A unique identifier for the SRT playback stream. This ID is used to distinguish between different playback streams
   */
  srtPlaybackStreamId?: string | undefined;
  /**
   * A playback secret used for securing the SRT playback stream. This ensures that only authorized users can access the playback
   */
  srtPlaybackSecret?: string | undefined;
};

/** @internal */
export const SrtPlaybackResponse$inboundSchema: z.ZodMiniType<
  SrtPlaybackResponse,
  unknown
> = z.object({
  srtPlaybackStreamId: types.optional(types.string()),
  srtPlaybackSecret: types.optional(types.string()),
});

export function srtPlaybackResponseFromJSON(
  jsonString: string,
): SafeParseResult<SrtPlaybackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SrtPlaybackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SrtPlaybackResponse' from JSON`,
  );
}
