/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { LanguageCode, LanguageCode$outboundSchema } from "./languagecode.js";

/**
 * Generates subtitle files for audio/video files.
 */
export type SubtitleInput = {
  /**
   * Defines the type of input.
   *
   * @remarks
   */
  type: string;
  /**
   * The direct URL of the subtitle file.
   */
  url: string;
  /**
   * Name of the language in which the subtitles will be generated.
   */
  languageName: string;
  /**
   * Language code for content localization
   */
  languageCode?: LanguageCode | undefined;
};

/** @internal */
export type SubtitleInput$Outbound = {
  type: string;
  url: string;
  languageName: string;
  languageCode: string;
};

/** @internal */
export const SubtitleInput$outboundSchema: z.ZodMiniType<
  SubtitleInput$Outbound,
  SubtitleInput
> = z.object({
  type: z.string(),
  url: z.string(),
  languageName: z.string(),
  languageCode: z._default(LanguageCode$outboundSchema, "en-US"),
});

export function subtitleInputToJSON(subtitleInput: SubtitleInput): string {
  return JSON.stringify(SubtitleInput$outboundSchema.parse(subtitleInput));
}
