/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * views affected by the specific errors.
 */
export type TopErrorDetailsPercentage = number | number;

/**
 * percentage of unique viewers affected by the specific error.
 */
export type UniqueViewersEffectedPercentage = number | number;

export type TopErrorDetails = {
  /**
   * views affected by the specific errors.
   */
  percentage?: number | number | null | undefined;
  /**
   * percentage of unique viewers affected by the specific error.
   */
  uniqueViewersEffectedPercentage?: number | number | null | undefined;
  /**
   * Information about the specific error.
   */
  notes?: string | null | undefined;
  /**
   * error message or description.
   */
  message?: string | null | undefined;
  /**
   * The timestamp of when the error was last observed.
   */
  lastSeen?: string | null | undefined;
  /**
   * Number of occurrences of the specific error.
   */
  count?: number | null | undefined;
  /**
   * Error code associated with the specific error.
   */
  code?: string | null | undefined;
};

/** @internal */
export const TopErrorDetailsPercentage$inboundSchema: z.ZodMiniType<
  TopErrorDetailsPercentage,
  unknown
> = smartUnion([types.number(), types.number()]);

export function topErrorDetailsPercentageFromJSON(
  jsonString: string,
): SafeParseResult<TopErrorDetailsPercentage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopErrorDetailsPercentage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopErrorDetailsPercentage' from JSON`,
  );
}

/** @internal */
export const UniqueViewersEffectedPercentage$inboundSchema: z.ZodMiniType<
  UniqueViewersEffectedPercentage,
  unknown
> = smartUnion([types.number(), types.number()]);

export function uniqueViewersEffectedPercentageFromJSON(
  jsonString: string,
): SafeParseResult<UniqueViewersEffectedPercentage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UniqueViewersEffectedPercentage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UniqueViewersEffectedPercentage' from JSON`,
  );
}

/** @internal */
export const TopErrorDetails$inboundSchema: z.ZodMiniType<
  TopErrorDetails,
  unknown
> = z.object({
  percentage: z.optional(
    z.nullable(smartUnion([types.number(), types.number()])),
  ),
  uniqueViewersEffectedPercentage: z.optional(
    z.nullable(smartUnion([types.number(), types.number()])),
  ),
  notes: z.optional(z.nullable(types.string())),
  message: z.optional(z.nullable(types.string())),
  lastSeen: z.optional(z.nullable(types.string())),
  count: z.optional(z.nullable(types.number())),
  code: z.optional(z.nullable(types.string())),
});

export function topErrorDetailsFromJSON(
  jsonString: string,
): SafeParseResult<TopErrorDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopErrorDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopErrorDetails' from JSON`,
  );
}
