/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { LanguageCode, LanguageCode$outboundSchema } from "./languagecode.js";

/**
 * Contains details for generating subtitle tracks for a media file.
 */
export type TrackSubtitlesGenerateRequest = {
  /**
   * The full name of the language used to generate the subtitles.
   */
  languageName?: string | undefined;
  /**
   * You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
   *
   * @remarks
   */
  metadata?: { [k: string]: string } | undefined;
  /**
   * Language code for content localization
   */
  languageCode?: LanguageCode | undefined;
};

/** @internal */
export type TrackSubtitlesGenerateRequest$Outbound = {
  languageName: string;
  metadata?: { [k: string]: string } | undefined;
  languageCode: string;
};

/** @internal */
export const TrackSubtitlesGenerateRequest$outboundSchema: z.ZodMiniType<
  TrackSubtitlesGenerateRequest$Outbound,
  TrackSubtitlesGenerateRequest
> = z.object({
  languageName: z._default(z.string(), "English"),
  metadata: z.optional(z.record(z.string(), z.string())),
  languageCode: z._default(LanguageCode$outboundSchema, "en-US"),
});

export function trackSubtitlesGenerateRequestToJSON(
  trackSubtitlesGenerateRequest: TrackSubtitlesGenerateRequest,
): string {
  return JSON.stringify(
    TrackSubtitlesGenerateRequest$outboundSchema.parse(
      trackSubtitlesGenerateRequest,
    ),
  );
}
