/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TracksSubtitles = {
  /**
   * Current status of the generated subtitle track.
   */
  status?: string | undefined;
  /**
   * URL of the generated subtitle file (VTT). Null while preparing.
   */
  url?: string | null | undefined;
};

/** @internal */
export const TracksSubtitles$inboundSchema: z.ZodMiniType<
  TracksSubtitles,
  unknown
> = z.object({
  status: types.optional(types.string()),
  url: z.optional(z.nullable(types.string())),
});

export function tracksSubtitlesFromJSON(
  jsonString: string,
): SafeParseResult<TracksSubtitles, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TracksSubtitles$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TracksSubtitles' from JSON`,
  );
}
