/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AccessPolicy, AccessPolicy$inboundSchema } from "./accesspolicy.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PolicyAction, PolicyAction$inboundSchema } from "./policyaction.js";

/**
 * Restrictions based on the originating domain of a request (for example, whether requests from certain websites must be allowed or blocked).
 */
export type UnusedUploadsPlaybackIdDomains = {
  /**
   * Policy action type
   */
  defaultPolicy?: PolicyAction | undefined;
  /**
   * A list of domains that are explicitly allowed access.
   */
  allow?: Array<string> | undefined;
  /**
   * A list of domains that are explicitly blocked from accessing the resource.
   */
  deny?: Array<string> | undefined;
};

/**
 * Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
 */
export type UnusedUploadsPlaybackIdUserAgents = {
  /**
   * Policy action type
   */
  defaultPolicy?: PolicyAction | undefined;
  /**
   * A list of specific user agents that are allowed to access the resource.
   */
  allow?: Array<string> | undefined;
  /**
   * A list of specific user agents that are blocked.
   */
  deny?: Array<string> | undefined;
};

/**
 * Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
 */
export type UnusedUploadsPlaybackIdAccessRestrictions = {
  /**
   * Restrictions based on the originating domain of a request (for example, whether requests from certain websites must be allowed or blocked).
   */
  domains?: UnusedUploadsPlaybackIdDomains | undefined;
  /**
   * Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
   */
  userAgents?: UnusedUploadsPlaybackIdUserAgents | undefined;
};

/**
 * A collection of Playback ID objects utilized for crafting HLS playback urls.
 */
export type UnusedUploadsPlaybackId = {
  /**
   * Access policy for media content
   */
  accessPolicy?: AccessPolicy | undefined;
  /**
   * Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
   */
  accessRestrictions?: UnusedUploadsPlaybackIdAccessRestrictions | undefined;
};

/** @internal */
export const UnusedUploadsPlaybackIdDomains$inboundSchema: z.ZodMiniType<
  UnusedUploadsPlaybackIdDomains,
  unknown
> = z.object({
  defaultPolicy: types.optional(PolicyAction$inboundSchema),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function unusedUploadsPlaybackIdDomainsFromJSON(
  jsonString: string,
): SafeParseResult<UnusedUploadsPlaybackIdDomains, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnusedUploadsPlaybackIdDomains$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnusedUploadsPlaybackIdDomains' from JSON`,
  );
}

/** @internal */
export const UnusedUploadsPlaybackIdUserAgents$inboundSchema: z.ZodMiniType<
  UnusedUploadsPlaybackIdUserAgents,
  unknown
> = z.object({
  defaultPolicy: types.optional(PolicyAction$inboundSchema),
  allow: types.optional(z.array(types.string())),
  deny: types.optional(z.array(types.string())),
});

export function unusedUploadsPlaybackIdUserAgentsFromJSON(
  jsonString: string,
): SafeParseResult<UnusedUploadsPlaybackIdUserAgents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnusedUploadsPlaybackIdUserAgents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnusedUploadsPlaybackIdUserAgents' from JSON`,
  );
}

/** @internal */
export const UnusedUploadsPlaybackIdAccessRestrictions$inboundSchema:
  z.ZodMiniType<UnusedUploadsPlaybackIdAccessRestrictions, unknown> = z.object({
    domains: types.optional(
      z.lazy(() => UnusedUploadsPlaybackIdDomains$inboundSchema),
    ),
    userAgents: types.optional(
      z.lazy(() => UnusedUploadsPlaybackIdUserAgents$inboundSchema),
    ),
  });

export function unusedUploadsPlaybackIdAccessRestrictionsFromJSON(
  jsonString: string,
): SafeParseResult<
  UnusedUploadsPlaybackIdAccessRestrictions,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UnusedUploadsPlaybackIdAccessRestrictions$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UnusedUploadsPlaybackIdAccessRestrictions' from JSON`,
  );
}

/** @internal */
export const UnusedUploadsPlaybackId$inboundSchema: z.ZodMiniType<
  UnusedUploadsPlaybackId,
  unknown
> = z.object({
  accessPolicy: types.optional(AccessPolicy$inboundSchema),
  accessRestrictions: types.optional(
    z.lazy(() => UnusedUploadsPlaybackIdAccessRestrictions$inboundSchema),
  ),
});

export function unusedUploadsPlaybackIdFromJSON(
  jsonString: string,
): SafeParseResult<UnusedUploadsPlaybackId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnusedUploadsPlaybackId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnusedUploadsPlaybackId' from JSON`,
  );
}
