/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";

export type UpdatePlaylistRequest = {
  /**
   * New name to the playlist.
   */
  name: string;
  /**
   * Updated description to the playlist.
   */
  description: string;
};

/** @internal */
export type UpdatePlaylistRequest$Outbound = {
  name: string;
  description: string;
};

/** @internal */
export const UpdatePlaylistRequest$outboundSchema: z.ZodMiniType<
  UpdatePlaylistRequest$Outbound,
  UpdatePlaylistRequest
> = z.object({
  name: z.string(),
  description: z.string(),
});

export function updatePlaylistRequestToJSON(
  updatePlaylistRequest: UpdatePlaylistRequest,
): string {
  return JSON.stringify(
    UpdatePlaylistRequest$outboundSchema.parse(updatePlaylistRequest),
  );
}
