/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Specifies the type of track (audio or subtitle).
 */
export const UpdateTrackResponseType = {
  Audio: "audio",
  Subtitle: "subtitle",
} as const;
/**
 * Specifies the type of track (audio or subtitle).
 */
export type UpdateTrackResponseType = OpenEnum<typeof UpdateTrackResponseType>;

/**
 * Contains details about the track that was added or updated.
 */
export type UpdateTrackResponse = {
  /**
   * The unique identifier of the track.
   */
  id?: string | undefined;
  /**
   * Specifies the type of track (audio or subtitle).
   */
  type?: UpdateTrackResponseType | undefined;
  /**
   * The direct URL of the track file.
   */
  url?: string | undefined;
  /**
   * The BCP 47 language code representing the track's language.
   */
  languageCode?: string | undefined;
  /**
   * The full name of the language corresponding to the `languageCode`.
   */
  languageName?: string | undefined;
};

/** @internal */
export const UpdateTrackResponseType$inboundSchema: z.ZodMiniType<
  UpdateTrackResponseType,
  unknown
> = openEnums.inboundSchema(UpdateTrackResponseType);

/** @internal */
export const UpdateTrackResponse$inboundSchema: z.ZodMiniType<
  UpdateTrackResponse,
  unknown
> = z.object({
  id: types.optional(types.string()),
  type: types.optional(UpdateTrackResponseType$inboundSchema),
  url: types.optional(types.string()),
  languageCode: types.optional(types.string()),
  languageName: types.optional(types.string()),
});

export function updateTrackResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTrackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTrackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTrackResponse' from JSON`,
  );
}
