/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { PolicyAction, PolicyAction$outboundSchema } from "./policyaction.js";

/**
 * Restrictions based on the user agent
 */
export type UserAgentRestrictions = {
  /**
   * Policy action type
   */
  defaultPolicy?: PolicyAction | undefined;
  /**
   * A list of user agents that are explicitly allowed access
   */
  allow?: Array<string> | undefined;
  /**
   * A list of user agents that are explicitly denied access
   */
  deny?: Array<string> | undefined;
};

/** @internal */
export type UserAgentRestrictions$Outbound = {
  defaultPolicy?: string | undefined;
  allow?: Array<string> | undefined;
  deny?: Array<string> | undefined;
};

/** @internal */
export const UserAgentRestrictions$outboundSchema: z.ZodMiniType<
  UserAgentRestrictions$Outbound,
  UserAgentRestrictions
> = z.object({
  defaultPolicy: z.optional(PolicyAction$outboundSchema),
  allow: z.optional(z.array(z.string())),
  deny: z.optional(z.array(z.string())),
});

export function userAgentRestrictionsToJSON(
  userAgentRestrictions: UserAgentRestrictions,
): string {
  return JSON.stringify(
    UserAgentRestrictions$outboundSchema.parse(userAgentRestrictions),
  );
}
