/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ViewsList = {
  /**
   * The unique identifier for the viewing session of the user.
   *
   * @remarks
   */
  viewId?: string | undefined;
  /**
   * Operating System signifies the software platform utilized by the viewer
   *
   * @remarks
   */
  operatingSystem?: string | null | undefined;
  /**
   * The browser name of the viewer.
   *
   * @remarks
   */
  application?: string | null | undefined;
  /**
   * The start timestamp of the video view.
   *
   * @remarks
   */
  viewStartTime?: string | null | undefined;
  /**
   * The end timestamp of the video view.
   *
   * @remarks
   */
  viewEndTime?: string | null | undefined;
  /**
   * The title of the Video.
   *
   * @remarks
   */
  videoTitle?: string | null | undefined;
  /**
   * The code which represents specific issues or failures that occur during playback. These can be implementation specific.
   *
   * @remarks
   */
  errorCode?: string | null | undefined;
  /**
   * The notifications or messages that inform users or developers about issues or failures that have occurred during the playback representing error codes.
   *
   * @remarks
   */
  errorMessage?: string | null | undefined;
  /**
   * Country of the viewer.
   *
   * @remarks
   */
  country?: string | null | undefined;
  /**
   * The watch time represents the time spent watching the video including staruptime, playback time ,buffering time.
   *
   * @remarks
   */
  viewWatchTime?: number | null | undefined;
  /**
   * The viewer experience encapsulated in the form of score while watching the video.
   *
   * @remarks
   */
  qoeScore?: number | null | undefined;
};

/** @internal */
export const ViewsList$inboundSchema: z.ZodMiniType<ViewsList, unknown> = z
  .pipe(
    z.object({
      viewId: types.optional(types.string()),
      operatingSystem: z.optional(z.nullable(types.string())),
      application: z.optional(z.nullable(types.string())),
      viewStartTime: z.optional(z.nullable(types.string())),
      viewEndTime: z.optional(z.nullable(types.string())),
      videoTitle: z.optional(z.nullable(types.string())),
      errorCode: z.optional(z.nullable(types.string())),
      errorMessage: z.optional(z.nullable(types.string())),
      country: z.optional(z.nullable(types.string())),
      viewWatchTime: z.optional(z.nullable(types.number())),
      QoeScore: z.optional(z.nullable(types.number())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "QoeScore": "qoeScore",
      });
    }),
  );

export function viewsListFromJSON(
  jsonString: string,
): SafeParseResult<ViewsList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ViewsList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ViewsList' from JSON`,
  );
}
