/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of overlay (currently only supports "watermark").
 */
export const WatermarkInputType = {
  Watermark: "watermark",
} as const;
/**
 * Type of overlay (currently only supports "watermark").
 */
export type WatermarkInputType = ClosedEnum<typeof WatermarkInputType>;

/**
 * Horizontal alignment of the watermark.
 */
export const XAlign = {
  Left: "left",
  Center: "center",
  Right: "right",
} as const;
/**
 * Horizontal alignment of the watermark.
 */
export type XAlign = ClosedEnum<typeof XAlign>;

/**
 * Vertical alignment of the watermark.
 */
export const YAlign = {
  Top: "top",
  Middle: "middle",
  Bottom: "bottom",
} as const;
/**
 * Vertical alignment of the watermark.
 */
export type YAlign = ClosedEnum<typeof YAlign>;

export type Placement = {
  /**
   * Horizontal alignment of the watermark.
   */
  xAlign?: XAlign | undefined;
  /**
   * Horizontal margin from the edge of the video.
   */
  xMargin?: string | undefined;
  /**
   * Vertical alignment of the watermark.
   */
  yAlign?: YAlign | undefined;
  /**
   * Vertical margin from the edge of the video.
   */
  yMargin?: string | undefined;
};

/**
 * Contains configuration details for applying a watermark overlay to a video.
 *
 * @remarks
 * The watermark is placed over the media content during processing.
 * For detailed setup steps and customization options, refer to the
 * <a href="https://docs.fastpix.io/docs/watermark-your-videos" target="_blank">FastPix Watermark Guide</a>.
 */
export type WatermarkInput = {
  /**
   * Type of overlay (currently only supports "watermark").
   */
  type: WatermarkInputType;
  /**
   * URL of the watermark image.
   */
  url: string;
  placement?: Placement | undefined;
  /**
   * Width of the watermark in percentage or pixels.
   */
  width?: string | undefined;
  /**
   * Height of the watermark in percentage or pixels.
   */
  height?: string | undefined;
  /**
   * Opacity of the watermark in percentage.
   */
  opacity?: string | undefined;
};

/** @internal */
export const WatermarkInputType$outboundSchema: z.ZodMiniEnum<
  typeof WatermarkInputType
> = z.enum(WatermarkInputType);

/** @internal */
export const XAlign$outboundSchema: z.ZodMiniEnum<typeof XAlign> = z.enum(
  XAlign,
);

/** @internal */
export const YAlign$outboundSchema: z.ZodMiniEnum<typeof YAlign> = z.enum(
  YAlign,
);

/** @internal */
export type Placement$Outbound = {
  xAlign?: string | undefined;
  xMargin?: string | undefined;
  yAlign?: string | undefined;
  yMargin?: string | undefined;
};

/** @internal */
export const Placement$outboundSchema: z.ZodMiniType<
  Placement$Outbound,
  Placement
> = z.object({
  xAlign: z.optional(XAlign$outboundSchema),
  xMargin: z.optional(z.string()),
  yAlign: z.optional(YAlign$outboundSchema),
  yMargin: z.optional(z.string()),
});

export function placementToJSON(placement: Placement): string {
  return JSON.stringify(Placement$outboundSchema.parse(placement));
}

/** @internal */
export type WatermarkInput$Outbound = {
  type: string;
  url: string;
  placement?: Placement$Outbound | undefined;
  width?: string | undefined;
  height?: string | undefined;
  opacity?: string | undefined;
};

/** @internal */
export const WatermarkInput$outboundSchema: z.ZodMiniType<
  WatermarkInput$Outbound,
  WatermarkInput
> = z.object({
  type: WatermarkInputType$outboundSchema,
  url: z.string(),
  placement: z.optional(z.lazy(() => Placement$outboundSchema)),
  width: z.optional(z.string()),
  height: z.optional(z.string()),
  opacity: z.optional(z.string()),
});

export function watermarkInputToJSON(watermarkInput: WatermarkInput): string {
  return JSON.stringify(WatermarkInput$outboundSchema.parse(watermarkInput));
}
